"""Independent, source-backed OHLCV strategy definitions.

This module is intentionally data, not an expanding chain of implementation branches.
Every row below owns a different entry/exit/ranking expression.  A parameter preset is
never counted as another strategy; runtime customization is applied after selection.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from ai_graph.schemas import Condition, ConditionOperator


SOURCE_REGISTRY: dict[str, str] = {
    "jegadeesh_titman": (
        "https://onlinelibrary.wiley.com/doi/10.1111/j.1540-6261.1993.tb04702.x"
    ),
    "time_series_momentum": (
        "https://w4.stern.nyu.edu/facdir/lpederse/papers/TimeSeriesMomentum.pdf"
    ),
    "george_hwang_52_week_high": (
        "https://onlinelibrary.wiley.com/doi/10.1111/j.1540-6261.2004.00695.x"
    ),
    "lee_swaminathan_volume": (
        "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=92589"
    ),
    "moreira_muir_volatility": "https://www.nber.org/papers/w22208",
    "ang_low_volatility": "https://www.ruf.rice.edu/~yxing/AHXZ_011906.pdf",
    "brock_technical_rules": (
        "https://onlinelibrary.wiley.com/doi/10.1111/j.1540-6261.1992.tb04681.x"
    ),
    "faber_tactical": "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=962461",
    "talib_functions": "https://ta-lib.org/functions/",
    "quantconnect_indicators": (
        "https://www.quantconnect.com/docs/v2/writing-algorithms/indicators/supported-indicators"
    ),
    "lean_engine": "https://github.com/QuantConnect/Lean",
    "backtrader_strategies": "https://www.backtrader.com/docu/strategy-reference/",
    # Fundamental-factor sources for the value/quality/growth/multi-factor rows added in
    # v2.  These strategies use the point-in-time DART financials (per/roe/operating_margin
    # /debt_to_equity/operating_income/revenue and their up-streaks) the loader already
    # forward-fills onto every bar, so they extend the catalog beyond price-only technicals.
    "greenblatt_magic_formula": "https://www.magicformulainvesting.com/",
    "novy_marx_profitability": "https://rnm.simon.rochester.edu/research/OSoV.pdf",
    "asness_frazzini_pedersen_qmj": (
        "https://www.aqr.com/Insights/Research/Journal-Article/Quality-Minus-Junk"
    ),
    "frazzini_pedersen_bab": (
        "https://www.aqr.com/Insights/Research/Journal-Article/Betting-Against-Beta"
    ),
    "aqr_value_momentum": (
        "https://www.aqr.com/Insights/Research/Journal-Article/Value-and-Momentum-Everywhere"
    ),
}


@dataclass(frozen=True)
class IndicatorDefinition:
    key: str
    label: str
    plain_explanation: str
    formula: str
    derivation: str
    why_used: str
    source_keys: tuple[str, ...]


INDICATORS: dict[str, IndicatorDefinition] = {
    item.key: item
    for item in (
        IndicatorDefinition(
            "return",
            "기간 수익률",
            "지금 가격이 과거 가격보다 얼마나 올랐는지를 비율로 봅니다.",
            "R_N=P_t/P_{t-N}-1",
            "현재 종가를 N거래일 전 종가로 나눈 뒤 1을 뺍니다. 신호일 이후 가격은 쓰지 않습니다.",
            "상승 추세의 크기와 방향을 가장 직접적으로 비교할 수 있기 때문입니다.",
            ("jegadeesh_titman", "time_series_momentum"),
        ),
        IndicatorDefinition(
            "relative_strength",
            "상대강도",
            "같은 날 다른 종목보다 더 강하게 오른 종목인지 비교합니다.",
            "RS_N=R_{i,N}-mean_j(R_{j,N})",
            "각 종목 N일 수익률에서 그날 투자대상 전체의 평균 N일 수익률을 뺍니다.",
            "시장 전체가 오른 효과와 개별 종목의 강함을 분리하기 위해 사용합니다.",
            ("jegadeesh_titman",),
        ),
        IndicatorDefinition(
            "sma",
            "단순이동평균",
            "최근 가격을 똑같은 비중으로 평균 낸 추세선입니다.",
            "SMA_N=(P_t+...+P_{t-N+1})/N",
            "최근 N개 종가를 더해 N으로 나눕니다.",
            "하루의 잡음을 줄이고 추세 방향과 지지선 이탈을 보기 쉽기 때문입니다.",
            ("brock_technical_rules", "backtrader_strategies"),
        ),
        IndicatorDefinition(
            "ema",
            "지수이동평균",
            "최근 가격에 더 큰 무게를 주는 평균선입니다.",
            "EMA_t=alpha*P_t+(1-alpha)*EMA_{t-1}, alpha=2/(N+1)",
            "N으로 감쇠율을 정하고 전일 EMA에 당일 가격 변화를 재귀적으로 반영합니다.",
            "SMA보다 최근 추세 전환에 빠르게 반응하도록 사용합니다.",
            ("talib_functions", "quantconnect_indicators"),
        ),
        IndicatorDefinition(
            "volatility",
            "실현변동성",
            "최근 일별 수익률이 얼마나 크게 흔들렸는지를 연율로 표시합니다.",
            "sigma_N=stdev(r_{t-N+1:t})*sqrt(252)",
            "최근 N일 수익률의 표본 표준편차에 거래일 기준 제곱근 252를 곱합니다.",
            "같은 수익이라도 덜 흔들린 전략을 선호하고 위기 노출을 줄이기 위해 씁니다.",
            ("moreira_muir_volatility", "ang_low_volatility"),
        ),
        IndicatorDefinition(
            "high_proximity",
            "기간 고점 근접도",
            "현재 가격이 최근 고점에 얼마나 가까운지 0~1 비율로 봅니다.",
            "HProx_N=P_t/max(P_{t-N+1:t})",
            "현재 종가를 최근 N일 최고 종가로 나눕니다.",
            "절대 수익률만으로 놓칠 수 있는 기준점 효과와 지속 강도를 포착하기 위해 씁니다.",
            ("george_hwang_52_week_high",),
        ),
        IndicatorDefinition(
            "volume_ratio",
            "거래량 배수",
            "오늘 거래량이 평소보다 몇 배인지 보여줍니다.",
            "VR_N=V_t/mean(V_{t-N+1:t})",
            "당일 거래량을 최근 N일 평균 거래량으로 나눕니다.",
            "가격 움직임에 실제 시장 참여가 동반됐는지 확인해 약한 신호를 거르기 위해 씁니다.",
            ("lee_swaminathan_volume", "talib_functions"),
        ),
        IndicatorDefinition(
            "sharpe",
            "롤링 샤프 비율",
            "평균 수익을 전체 흔들림으로 나눈 위험 대비 수익 점수입니다.",
            "Sharpe_N=mean(r)/stdev(r)*sqrt(252)",
            "최근 N일 일별 수익률 평균을 표준편차로 나누고 연율화합니다. 무위험수익률은 0으로 둡니다.",
            "수익률만 높은 종목보다 경로가 안정적인 종목을 비교하기 위해 사용합니다.",
            ("moreira_muir_volatility",),
        ),
        IndicatorDefinition(
            "sortino",
            "롤링 소르티노 비율",
            "좋은 상승 변동은 벌점에서 빼고 하락 변동만 위험으로 보는 점수입니다.",
            "Sortino_N=mean(r)/sqrt(mean(min(r,0)^2))*sqrt(252)",
            "최근 수익률 중 0 아래인 값만 제곱평균해 하방편차를 만들고 평균수익을 나눕니다.",
            "사용자가 실제로 불편해하는 하락 흔들림에 집중하기 위해 씁니다.",
            ("quantconnect_indicators",),
        ),
        IndicatorDefinition(
            "calmar",
            "롤링 칼마 비율",
            "연환산 수익을 같은 기간 최악 낙폭으로 나눈 점수입니다.",
            "Calmar_N=annualized_return_N/abs(max_drawdown_N)",
            "기간 총수익을 연율화하고, 그 기간 누적 경로의 고점 대비 최대 하락폭으로 나눕니다.",
            "큰 중간 손실을 감수해 얻은 수익과 완만한 수익을 구분하기 위해 씁니다.",
            ("quantconnect_indicators",),
        ),
        IndicatorDefinition(
            "momentum_blend",
            "다중기간 모멘텀",
            "단기·중기·장기 상승을 한 점수로 합칩니다.",
            "Blend=.5*R_63+.3*R_126+.2*R_252",
            "세 기간 수익률을 미리 고정한 비중으로 합산합니다. 백테스트 결과를 보고 비중을 바꾸지 않습니다.",
            "한 기간의 우연한 급등에 덜 의존하면서 추세의 지속성을 확인하기 위해 씁니다.",
            ("jegadeesh_titman", "time_series_momentum"),
        ),
        IndicatorDefinition(
            "macd",
            "MACD",
            "빠른 EMA와 느린 EMA의 간격으로 추세 가속을 봅니다.",
            "MACD=EMA_12-EMA_26; Signal=EMA_9(MACD)",
            "12일 EMA에서 26일 EMA를 빼고 그 결과의 9일 EMA를 신호선으로 만듭니다.",
            "추세 방향뿐 아니라 빨라지는 시점과 느려지는 시점을 잡기 위해 씁니다.",
            ("talib_functions", "quantconnect_indicators"),
        ),
        IndicatorDefinition(
            "ppo",
            "PPO",
            "MACD 간격을 느린 EMA로 나눠 가격 수준이 다른 종목도 비교하게 합니다.",
            "PPO=100*(EMA_12-EMA_26)/EMA_26",
            "두 EMA의 차이를 26일 EMA로 나누고 100을 곱한 뒤 9일 EMA 신호선을 만듭니다.",
            "만원짜리와 백만원짜리 종목의 추세 강도를 같은 비율 단위로 비교하기 위해 씁니다.",
            ("talib_functions",),
        ),
        IndicatorDefinition(
            "adx",
            "ADX와 방향지표",
            "ADX는 추세의 세기, +DI/-DI는 상승·하락 어느 쪽이 강한지 나타냅니다.",
            "ADX=WilderMean(100*abs(+DI--DI)/(+DI+-DI))",
            "고가·저가 변화와 진폭을 14일 Wilder 방식으로 평활해 +DI, -DI, ADX를 계산합니다.",
            "방향 없는 횡보장에서 이동평균 신호가 자주 뒤집히는 문제를 줄이기 위해 씁니다.",
            ("talib_functions", "quantconnect_indicators"),
        ),
        IndicatorDefinition(
            "aroon",
            "Aroon",
            "최근 고점·저점이 얼마나 최근에 나왔는지를 시간으로 측정합니다.",
            "AroonUp=100*(N-days_since_high)/N",
            "N일 창에서 최고가와 최저가가 발생한 뒤 지난 일수를 0~100 점수로 바꿉니다.",
            "가격 크기보다 새 고점이 계속 갱신되는 시간 구조를 보기 위해 씁니다.",
            ("talib_functions",),
        ),
        IndicatorDefinition(
            "slope",
            "선형회귀 기울기",
            "최근 가격을 가장 잘 설명하는 직선의 하루 상승률과 설명력을 봅니다.",
            "slope=sum((x-xbar)(P-Pbar))/sum((x-xbar)^2)/Pbar",
            "N일 종가에 최소제곱 직선을 맞추고 가격 수준으로 나눠 정규화하며 R제곱도 계산합니다.",
            "들쭉날쭉한 급등보다 일정한 경사의 추세를 찾기 위해 사용합니다.",
            ("talib_functions", "quantconnect_indicators"),
        ),
        IndicatorDefinition(
            "efficiency",
            "Kaufman 효율비율",
            "출발점부터 이동한 거리와 매일 움직인 총거리의 비율입니다.",
            "ER_N=abs(P_t-P_{t-N})/sum(abs(P_k-P_{k-1}))",
            "N일 순변화를 같은 기간 매일의 절대변화 합으로 나눠 0~1로 만듭니다.",
            "직선적인 추세와 제자리에서 요동한 움직임을 구분하기 위해 씁니다.",
            ("quantconnect_indicators",),
        ),
        IndicatorDefinition(
            "trix",
            "TRIX",
            "세 번 평활한 EMA의 변화율로 아주 짧은 잡음을 줄인 추세 가속도입니다.",
            "TRIX=100*(EMA3_t/EMA3_{t-1}-1)",
            "종가에 같은 기간 EMA를 세 번 적용하고 마지막 EMA의 하루 변화율을 계산합니다.",
            "잡음이 많은 종목에서 느리지만 명확한 추세 전환을 찾기 위해 씁니다.",
            ("talib_functions",),
        ),
        IndicatorDefinition(
            "supertrend",
            "Supertrend",
            "ATR만큼 여유를 둔 추적선 위인지 아래인지로 추세 상태를 정합니다.",
            "basic bands=(H+L)/2 +/- 3*ATR_10",
            "기본 밴드를 계산한 뒤 전일 밴드와 종가에 따라 밴드를 끌어올리거나 내리고 방향을 상태로 유지합니다.",
            "변동성이 큰 종목에 고정 퍼센트보다 넓은 숨 쉴 공간을 주기 위해 씁니다.",
            ("quantconnect_indicators",),
        ),
        IndicatorDefinition(
            "donchian",
            "Donchian 채널",
            "직전 N일 최고가와 최저가를 돌파선으로 사용합니다.",
            "Upper_N=max(H_{t-N:t-1}); Lower_N=min(L_{t-N:t-1})",
            "오늘을 제외한 직전 N개 고가·저가의 최대·최소를 계산합니다.",
            "오늘 가격을 오늘 포함 고점과 비교하는 자기참조를 피하면서 새 추세를 확인하기 위해 씁니다.",
            ("brock_technical_rules", "quantconnect_indicators"),
        ),
        IndicatorDefinition(
            "bollinger",
            "볼린저 밴드",
            "이동평균에서 최근 표준편차 두 배만큼 떨어진 동적 가격 범위입니다.",
            "Middle=SMA_20; Upper/Lower=Middle+/-2*std_20",
            "20일 종가 평균과 모집단 표준편차로 위·아래 밴드를 만듭니다.",
            "평소 변동폭을 기준으로 이례적 돌파와 과매도를 같은 단위로 판단하기 위해 씁니다.",
            ("talib_functions", "quantconnect_indicators"),
        ),
        IndicatorDefinition(
            "keltner",
            "Keltner 채널",
            "EMA 주변에 ATR 배수만큼 폭을 둔 추세 채널입니다.",
            "Middle=EMA_20; Upper/Lower=Middle+/-2*ATR_10",
            "20일 EMA와 10일 ATR을 계산해 상하단을 만듭니다.",
            "표준편차 대신 실제 고저 범위를 반영해 갭이 잦은 종목의 돌파를 보기 위해 씁니다.",
            ("quantconnect_indicators",),
        ),
        IndicatorDefinition(
            "atr",
            "ATR",
            "갭까지 포함한 하루 실제 가격 범위의 평활 평균입니다.",
            "TR=max(H-L,abs(H-C_prev),abs(L-C_prev)); ATR=WilderMean(TR)",
            "매일 세 범위 중 최댓값을 구하고 Wilder 방식으로 N일 평활합니다.",
            "종목별 평상시 움직임에 맞춘 돌파와 손절 폭을 만들기 위해 씁니다.",
            ("talib_functions",),
        ),
        IndicatorDefinition(
            "squeeze",
            "변동성 스퀴즈",
            "가격 밴드가 평소보다 좁아진 뒤 위로 빠져나오는지를 찾습니다.",
            "Squeeze=(BBWidth_20 < .6*mean(BBWidth_120)) and P>DonchianHigh_20",
            "20일 볼린저 폭을 직전 120일 평균과 비교하고 직전 20일 고점 돌파를 결합합니다.",
            "에너지가 압축된 횡보 뒤 큰 방향 움직임이 시작되는 후보를 찾기 위해 씁니다.",
            ("quantconnect_indicators",),
        ),
        IndicatorDefinition(
            "nr7",
            "NR7 돌파",
            "직전 봉의 범위가 7일 중 가장 좁은 뒤 그 고점을 넘는 패턴입니다.",
            "NR7Break=(Range_{t-1}=min(Range_{t-7:t-1})) and P_t>H_{t-1}",
            "전일 고가-저가가 그 전 7개 봉 중 최소인지 확인한 다음 당일 종가 돌파를 봅니다.",
            "짧은 변동성 압축 후 확장을 단순하고 재현 가능한 규칙으로 잡기 위해 씁니다.",
            ("lean_engine",),
        ),
        IndicatorDefinition(
            "candle_pattern",
            "봉 범위 패턴",
            "고가·저가가 전일 범위 안/밖에 있는지와 종가 방향을 봅니다.",
            "Inside: H_{t-1}<H_{t-2} and L_{t-1}>L_{t-2}",
            "두 봉의 고가와 저가를 직접 비교하고 다음 봉 종가가 기준 범위를 넘었는지 확인합니다.",
            "복잡한 주관적 차트 이름 대신 OHLC 네 값으로 검증 가능한 압축·확장을 표현하기 위해 씁니다.",
            ("lean_engine", "backtrader_strategies"),
        ),
        IndicatorDefinition(
            "gap",
            "갭 수익률",
            "오늘 시가가 전일 종가에서 얼마나 떨어져 시작했는지 봅니다.",
            "Gap_t=O_t/C_{t-1}-1",
            "당일 시가를 같은 종목 전일 종가로 나누고 1을 뺍니다.",
            "장중 추세와 밤사이 정보 충격을 분리해 돌파 또는 과잉반응을 판단하기 위해 씁니다.",
            ("lean_engine",),
        ),
        IndicatorDefinition(
            "range_expansion",
            "가격 범위 확장",
            "오늘 실제 범위가 평소 ATR보다 얼마나 큰지 봅니다.",
            "Expansion=TR_t/ATR_20",
            "당일 True Range를 20일 ATR로 나누고 종가가 봉 상단과 직전 고점 위인지 함께 확인합니다.",
            "작은 고점 돌파보다 수급이 실린 큰 방향 봉을 구분하기 위해 씁니다.",
            ("talib_functions",),
        ),
        IndicatorDefinition(
            "rsi",
            "RSI",
            "최근 상승폭과 하락폭의 비율을 0~100으로 바꾼 과열·침체 지표입니다.",
            "RSI=100-100/(1+WilderAvg(gain)/WilderAvg(loss))",
            "14일 상승분과 하락분을 각각 Wilder 평활한 뒤 상대강도를 0~100으로 변환합니다.",
            "단기 하락이 과도했는지와 반등 후 과열됐는지를 같은 축으로 보기 위해 씁니다.",
            ("talib_functions",),
        ),
        IndicatorDefinition(
            "zscore",
            "가격 Z점수",
            "현재 가격이 최근 평균에서 표준편차 몇 배 떨어졌는지 나타냅니다.",
            "Z_N=(P_t-SMA_N)/std(P_N)",
            "현재 종가에서 N일 평균을 뺀 뒤 같은 기간 종가 표준편차로 나눕니다.",
            "가격 수준이 다른 종목의 이례적 이탈을 동일한 단위로 비교하기 위해 씁니다.",
            ("quantconnect_indicators",),
        ),
        IndicatorDefinition(
            "stochastic",
            "스토캐스틱",
            "현재 종가가 최근 고저 범위의 어디에 있는지 0~100으로 표시합니다.",
            "%K=100*(C-L_N)/(H_N-L_N); %D=SMA_3(%K)",
            "14일 최저가와 최고가 사이의 종가 위치를 계산하고 3일 평균을 신호선으로 씁니다.",
            "박스권에서 하단 이탈 후 되돌림을 가격 범위 기준으로 확인하기 위해 씁니다.",
            ("talib_functions",),
        ),
        IndicatorDefinition(
            "williams_r",
            "Williams %R",
            "종가가 최근 최고가에서 얼마나 아래인지 -100~0으로 표시합니다.",
            "%R=-100*(H_N-C)/(H_N-L_N)",
            "14일 최고·최저와 현재 종가의 거리를 비율로 계산합니다.",
            "스토캐스틱과 반대 방향 축으로 과매도 구간을 간결하게 확인하기 위해 씁니다.",
            ("talib_functions",),
        ),
        IndicatorDefinition(
            "cci",
            "CCI",
            "전형가격이 최근 평균에서 평균절대편차 몇 배 벗어났는지 봅니다.",
            "CCI=(TP-SMA(TP))/(.015*mean(abs(TP-SMA(TP))))",
            "고가·저가·종가 평균인 TP의 20일 평균과 평균절대편차를 사용합니다.",
            "표준편차 대신 평균절대편차로 순환적 과매도·과매수를 잡기 위해 씁니다.",
            ("talib_functions",),
        ),
        IndicatorDefinition(
            "mfi",
            "MFI",
            "가격 방향에 거래량을 함께 넣은 0~100 자금흐름 지표입니다.",
            "MFI=100-100/(1+positive_money_flow/negative_money_flow)",
            "전형가격×거래량을 전형가격 상승일과 하락일로 나눠 14일 합계를 비교합니다.",
            "가격만 과매도인 경우와 실제 거래대금 유출이 동반된 경우를 구분하기 위해 씁니다.",
            ("talib_functions",),
        ),
        IndicatorDefinition(
            "vwap",
            "롤링 VWAP",
            "거래량이 많이 실린 가격에 더 큰 비중을 준 평균가격입니다.",
            "VWAP_N=sum(TP*V)/sum(V)",
            "전형가격에 거래량을 곱한 N일 합을 거래량 합으로 나눕니다.",
            "최근 시장 참여자의 평균 체결 원가에서 크게 이탈했는지 보기 위해 씁니다.",
            ("quantconnect_indicators",),
        ),
        IndicatorDefinition(
            "loss_streak",
            "연속 하락일",
            "종가가 전일보다 내린 날이 몇 번 연속됐는지 셉니다.",
            "Streak_t = Streak_{t-1}+1 if P_t<P_{t-1} else 0",
            "같은 종목의 과거 종가만 순서대로 비교해 하락이 끊길 때 0으로 초기화합니다.",
            "한 번의 급락과 여러 날 누적된 매도 압력을 구분하기 위해 씁니다.",
            ("lean_engine",),
        ),
        IndicatorDefinition(
            "obv",
            "OBV",
            "상승일 거래량은 더하고 하락일 거래량은 빼 누적 수급을 봅니다.",
            "OBV_t=OBV_{t-1}+sign(C_t-C_{t-1})*V_t",
            "종가 방향에 따라 당일 거래량을 누적하고 최근 회귀 기울기를 계산합니다.",
            "가격보다 먼저 누적되는 매수·매도 참여의 방향을 확인하기 위해 씁니다.",
            ("talib_functions",),
        ),
        IndicatorDefinition(
            "cmf",
            "Chaikin Money Flow",
            "봉 안에서 종가 위치와 거래량을 결합한 누적 매수 압력입니다.",
            "CMF_N=sum(((2C-H-L)/(H-L))*V)/sum(V)",
            "각 봉의 자금흐름 승수에 거래량을 곱해 20일 합산하고 거래량 합으로 나눕니다.",
            "고가 부근 대량 마감과 저가 부근 대량 마감을 다르게 평가하기 위해 씁니다.",
            ("quantconnect_indicators",),
        ),
        IndicatorDefinition(
            "adl",
            "Accumulation/Distribution Line",
            "CMF의 일별 자금흐름량을 계속 누적한 수급선입니다.",
            "ADL_t=ADL_{t-1}+((2C-H-L)/(H-L))*V",
            "봉 내 종가 위치로 거래량의 부호와 크기를 정해 누적하고 최근 기울기를 봅니다.",
            "가격 횡보 중에도 누적 매집 또는 분산이 진행되는지 찾기 위해 씁니다.",
            ("talib_functions",),
        ),
        IndicatorDefinition(
            "pvi",
            "Positive Volume Index",
            "거래량이 전일보다 늘어난 날의 수익률만 누적합니다.",
            "PVI_t=PVI_{t-1}*(1+r_t) if V_t>V_{t-1}",
            "1000에서 시작해 거래량 증가일에만 종가 수익률을 반영하고 100일 평균과 비교합니다.",
            "활발한 참여가 생긴 날의 가격 방향이 장기 추세와 같은지 보기 위해 씁니다.",
            ("quantconnect_indicators",),
        ),
        IndicatorDefinition(
            "nvi",
            "Negative Volume Index",
            "거래량이 줄어든 조용한 날의 수익률만 누적합니다.",
            "NVI_t=NVI_{t-1}*(1+r_t) if V_t<V_{t-1}",
            "1000에서 시작해 거래량 감소일에만 수익률을 반영하고 100일 평균과 비교합니다.",
            "소음이 줄어든 날에도 유지되는 기초 추세를 확인하기 위해 씁니다.",
            ("quantconnect_indicators",),
        ),
        IndicatorDefinition(
            "force_index",
            "Force Index",
            "가격 변화에 거래량을 곱해 매수·매도 힘을 측정합니다.",
            "Force=(C_t-C_{t-1})*V_t; FI=EMA_13(Force)",
            "종가 변화액과 당일 거래량의 곱을 13일 EMA로 평활합니다.",
            "작은 거래량의 상승과 큰 거래량의 상승을 힘의 크기로 구분하기 위해 씁니다.",
            ("quantconnect_indicators",),
        ),
        IndicatorDefinition(
            "eom",
            "Ease of Movement",
            "가격 이동 거리 대비 필요한 거래량과 봉 폭을 비교합니다.",
            "EOM=((Mid_t-Mid_{t-1})*(H-L))/V; EOM14=SMA_14(EOM)",
            "고저 중간값 변화에 봉 폭을 곱하고 거래량으로 나눈 뒤 14일 평균합니다.",
            "적은 저항으로 위로 움직이는 종목과 힘겹게 오르는 종목을 구분하기 위해 씁니다.",
            ("quantconnect_indicators",),
        ),
        IndicatorDefinition(
            "pvo",
            "PVO",
            "단기·장기 거래량 EMA의 차이를 비율로 나타냅니다.",
            "PVO=100*(EMA_12(V)-EMA_26(V))/EMA_26(V)",
            "거래량의 12일·26일 EMA 차이를 26일 EMA로 나누고 9일 신호선을 만듭니다.",
            "절대 거래량이 다른 종목 사이에서도 참여가 빨라지는 시점을 비교하기 위해 씁니다.",
            ("talib_functions",),
        ),
        IndicatorDefinition(
            "ulcer",
            "Ulcer Index",
            "최근 고점 아래에서 머문 하락폭의 제곱평균입니다.",
            "UI_N=sqrt(mean((100*(P/rolling_peak-1))^2))",
            "N일 창 안에서 각 시점의 고점 대비 하락률을 제곱평균한 뒤 제곱근을 취합니다.",
            "상하 변동을 똑같이 벌주는 변동성과 달리 오래 지속되는 손실 스트레스만 보기 위해 씁니다.",
            ("quantconnect_indicators",),
        ),
        IndicatorDefinition(
            "drawdown",
            "낙폭과 회복",
            "최근 고점에서 얼마나 빠졌고 다시 얼마나 회복했는지 봅니다.",
            "DD_N=P_t/max(P_N)-1; Recovery=R_20/abs(DD_63)",
            "기간 최고 종가 대비 현재 하락률과 최근 20일 반등률의 비율을 결합합니다.",
            "단순 저가매수보다 실제로 반등 힘이 생긴 낙폭 종목만 고르기 위해 씁니다.",
            ("quantconnect_indicators",),
        ),
        # Point-in-time DART fundamentals.  The warehouse loader forward-fills each of
        # these onto every trading-day bar (only filings dated strictly before the bar),
        # so a rule referencing them is backtested on the same next-open engine as the
        # price-only rows - not a screen-only concept.
        IndicatorDefinition(
            "per",
            "PER (주가수익비율)",
            "주가가 한 해 벌어들인 순이익의 몇 배인지 나타내는 저평가·고평가 척도입니다.",
            "PER=종가/주당순이익(EPS)",
            "그 날 시점에 공시된 연간 EPS로 당일 종가를 나눕니다. EPS가 0 이하인 적자 기업은 값을 두지 않아 저평가 화면에 적자기업이 섞이지 않습니다.",
            "이익 대비 얼마나 싸게 거래되는지를 종목 간 같은 기준으로 비교하기 위해 씁니다.",
            ("greenblatt_magic_formula", "aqr_value_momentum"),
        ),
        IndicatorDefinition(
            "roe",
            "ROE (자기자본이익률)",
            "회사가 자기자본으로 얼마나 효율적으로 이익을 냈는지를 비율로 봅니다.",
            "ROE=당기순이익/자기자본",
            "그 시점에 공시된 순이익을 자기자본으로 나눕니다. 지속적으로 높은 ROE는 자본을 잘 굴리는 우량기업의 대표 신호입니다.",
            "가격 신호와 무관하게 사업 자체의 수익성·질을 걸러내기 위해 씁니다.",
            ("novy_marx_profitability", "asness_frazzini_pedersen_qmj"),
        ),
        IndicatorDefinition(
            "operating_margin",
            "영업이익률",
            "매출 100원당 본업에서 남긴 영업이익이 몇 원인지 보여줍니다.",
            "OPM=영업이익/매출액",
            "그 시점 공시된 영업이익을 매출액으로 나눕니다. 자산 대비 총이익을 쓰는 Novy-Marx의 원지표와 달라 자산집약 업종은 낮게 나올 수 있습니다.",
            "본업의 마진 경쟁력과 수익성 지속성을 보기 위해 씁니다.",
            ("novy_marx_profitability",),
        ),
        IndicatorDefinition(
            "debt_to_equity",
            "부채비율 (D/E)",
            "자기자본 대비 빚이 얼마나 많은지를 비율로 나타내는 안전성 지표입니다.",
            "D/E=총부채/자기자본",
            "그 시점 공시된 총부채를 자기자본으로 나눕니다. 값이 낮을수록 재무 레버리지가 작아 하락장에서 더 견디는 경향이 있습니다.",
            "수익성만 높고 빚으로 떠받친 기업을 걸러 방어형·우량 조건을 만들기 위해 씁니다.",
            ("asness_frazzini_pedersen_qmj", "frazzini_pedersen_bab"),
        ),
        IndicatorDefinition(
            "fundamental_growth_streak",
            "펀더멘털 연속증가 분기수",
            "매출·영업이익 등이 직전 분기보다 늘어난 흐름이 몇 분기 연속됐는지 셉니다.",
            "Streak_t=Streak_{t-1}+1 if X_t>X_{t-1} else 0",
            "각 공시에서 지표가 직전 공시보다 크면 카운트를 1 늘리고 아니면 0으로 초기화한 값을 바에 실어둡니다. YoY가 아닌 직전분기 대비라 계절적 비수기 하락에 끊길 수 있습니다.",
            "한 번의 호실적이 아니라 여러 분기 지속된 개선을 성장의 대리 신호로 쓰기 위해 씁니다.",
            ("greenblatt_magic_formula", "novy_marx_profitability"),
        ),
    )
}


RiskStyle = Literal["aggressive", "balanced", "defensive"]
InvestmentHorizon = Literal["short", "medium", "long"]
ExecutionMode = Literal["event_driven", "scheduled_rotation"]


@dataclass(frozen=True)
class StrategyRuleDefinition:
    strategy_id: str
    family: str
    title: str
    plain_explanation: str
    formula: str
    derivation: str
    why_used: str
    entry_conditions: tuple[Condition, ...]
    exit_conditions: tuple[Condition, ...]
    ranking_metric: str
    ranking_direction: Literal["desc", "asc"]
    execution_mode: ExecutionMode
    lookback: int
    threshold: float
    risk_style: RiskStyle
    horizon: InvestmentHorizon
    default_priority: int
    indicator_keys: tuple[str, ...]
    tags: tuple[str, ...]
    source_keys: tuple[str, ...]
    caveat: str


def _c(
    left: str,
    operator: ConditionOperator,
    right: float | str | list[float],
    **kwargs: object,
) -> Condition:
    return Condition(left=left, operator=operator, right=right, **kwargs)


GT = ConditionOperator.GT
GTE = ConditionOperator.GTE
LT = ConditionOperator.LT
LTE = ConditionOperator.LTE
CROSS_ABOVE = ConditionOperator.CROSS_ABOVE
CROSS_BELOW = ConditionOperator.CROSS_BELOW


def _r(
    strategy_id: str,
    family: str,
    title: str,
    plain: str,
    formula: str,
    derivation: str,
    why: str,
    entry: tuple[Condition, ...],
    exit: tuple[Condition, ...],
    ranking: str,
    indicators: tuple[str, ...],
    tags: tuple[str, ...],
    sources: tuple[str, ...],
    *,
    lookback: int,
    threshold: float = 0.0,
    direction: Literal["desc", "asc"] = "desc",
    mode: ExecutionMode = "event_driven",
    risk: RiskStyle = "balanced",
    horizon: InvestmentHorizon = "medium",
    priority: int = 50,
    caveat: str = "횡보장·급격한 체제 전환에서는 신호가 반복해서 틀릴 수 있습니다.",
) -> StrategyRuleDefinition:
    return StrategyRuleDefinition(
        strategy_id=strategy_id,
        family=family,
        title=title,
        plain_explanation=plain,
        formula=formula,
        derivation=derivation,
        why_used=why,
        entry_conditions=entry,
        exit_conditions=exit,
        ranking_metric=ranking,
        ranking_direction=direction,
        execution_mode=mode,
        lookback=lookback,
        threshold=threshold,
        risk_style=risk,
        horizon=horizon,
        default_priority=priority,
        indicator_keys=indicators,
        tags=tags,
        source_keys=sources,
        caveat=caveat,
    )


# 56 independent formulas.  Different windows of the same formula are not listed as
# separate strategies; every row changes the economic signal or confirmation logic.
# Rows measured in the bottom third of the catalogue in BOTH non-overlapping five-year
# walk-forward windows on the production evaluator (2016-09-05..2021-09-03 and
# 2021-09-06..2026-09-04, KOSPI/KOSDAQ top-100 traded universe, 45 folds each; see
# 진행상황-수익률검증-수정-2026-09-07.md §8). They stay in the catalogue - a rule that
# lost in two windows is still a legitimate, cited formula a user may ask for by name -
# but they no longer outrank rows with two-window evidence when a vague request is
# routed by risk style and horizon alone. Demotion is a priority change, never a
# performance-fitted parameter change.
TWO_WINDOW_BOTTOM_THIRD_CAVEAT = (
    "두 개의 겹치지 않는 5년 구간(2016-09~2021-09, 2021-09~2026-09) walk-forward 실측에서 "
    "모두 카탈로그 하위 1/3에 들어 기본 추천 우선순위를 낮췄습니다. 지정 요청에는 그대로 실행됩니다."
)
TWO_WINDOW_DEMOTION = 40


STRATEGY_RULES: tuple[StrategyRuleDefinition, ...] = (
    _r(
        "cross-sectional-12-1-momentum", "momentum", "12-1 횡단면 모멘텀",
        "최근 한 달을 뺀 장기 상승률이 시장 상위 20%이고 장기 추세선 위인 종목을 순환 보유합니다.",
        "rank_top20(P[t-21]/P[t-252]-1); P>SMA_200",
        "252일 전부터 21일 전까지의 수익률을 계산해 최근 한 달을 명시적으로 건너뛰고, 200일 평균 위 조건을 더합니다.",
        "학술 모멘텀의 핵심인 승자 지속성과 장기 추세 확인을 함께 쓰기 위해 선택했습니다.",
        (_c("momentum_12_1", GTE, 0.0, universe_rank_pct=.20), _c("close", GT, "sma_200")),
        (_c("return_63d", LT, 0.0),), "momentum_12_1", ("return", "sma"),
        ("12-1", "횡단면", "모멘텀", "relative momentum"), ("jegadeesh_titman",),
        lookback=252, mode="scheduled_rotation", priority=100,
    ),
    _r(
        "time-series-absolute-momentum", "momentum", "시계열 절대 모멘텀",
        "다른 종목과 비교하지 않고 자기 자신의 12개월 수익이 양수인 종목만 보유합니다.",
        "R_252>0 and P>SMA_200; exit=R_63<0",
        "252일 전 가격 대비 수익률의 부호와 200일 평균 위치를 확인하고 63일 수익이 음수가 되면 나옵니다.",
        "시장 전체 약세 때 상대적으로 덜 나쁜 종목을 억지로 사는 문제를 줄이기 위해 씁니다.",
        (_c("return_252d", GT, 0.0), _c("close", GT, "sma_200")),
        (_c("return_63d", LT, 0.0),), "return_252d", ("return", "sma"),
        ("절대모멘텀", "시계열", "12개월", "time series momentum"), ("time_series_momentum",),
        lookback=252, mode="scheduled_rotation", horizon="long", priority=98,
    ),
    _r(
        "dual-momentum", "momentum", "듀얼 모멘텀",
        "장기 수익이 양수이면서 시장 대비 중기 강도가 상위인 종목만 고릅니다.",
        "R_252>0 and rank_top20(RS_126); rank=RS_126",
        "절대 필터 R252와 횡단면 상대강도 RS126을 AND로 결합해 둘 중 하나만 좋은 종목을 제외합니다.",
        "상승 체제 확인과 종목 간 리더 선정을 한 규칙에서 동시에 수행하기 위해 씁니다.",
        (_c("return_252d", GT, 0.0), _c("relative_strength_126d", GTE, 0.0, universe_rank_pct=.20)),
        (_c("return_63d", LT, 0.0),), "relative_strength_126d", ("return", "relative_strength"),
        ("듀얼", "상대강도", "절대모멘텀", "dual momentum"), ("jegadeesh_titman", "time_series_momentum"),
        lookback=252, mode="scheduled_rotation", priority=59,
        caveat=TWO_WINDOW_BOTTOM_THIRD_CAVEAT,
    ),
    _r(
        "risk-adjusted-momentum", "momentum", "위험조정 모멘텀",
        "중기 수익이 상위이면서 같은 기간 샤프 비율도 양수인 종목을 고릅니다.",
        "rank_top20(R_126) and Sharpe_126>0; rank=Sharpe_126",
        "126일 수익률 상위군을 만든 뒤 평균수익을 변동성으로 나눈 샤프 비율로 최종 순서를 정합니다.",
        "급등했지만 경로가 불안정한 종목보다 반복 가능한 상승 경로를 우선하기 위해 씁니다.",
        (_c("return_126d", GTE, 0.0, universe_rank_pct=.20), _c("sharpe_126", GT, 0.0)),
        (_c("sharpe_42", LT, 0.0),), "sharpe_126", ("return", "sharpe"),
        ("위험조정", "샤프", "risk adjusted momentum"), ("jegadeesh_titman", "moreira_muir_volatility"),
        lookback=126, mode="scheduled_rotation", priority=95,
    ),
    _r(
        "volatility-managed-momentum", "momentum", "변동성 관리 모멘텀",
        "수익 대비 변동성이 좋은 종목만 고르고 단기 변동성이 위험 수준을 넘으면 빠집니다.",
        "rank_top25(R_126/sigma_126) and sigma_21<35%; exit=sigma_21>50%",
        "126일 수익률을 126일 변동성으로 나눈 점수와 21일 연율 변동성 상한을 결합합니다.",
        "고변동 구간에서 기대수익보다 위험이 더 빨리 커질 때 노출을 줄이기 위해 씁니다.",
        (_c("return_vol_ratio_126", GTE, 0.0, universe_rank_pct=.25), _c("realized_volatility_21d", LT, .35)),
        (_c("realized_volatility_21d", GT, .50),), "return_vol_ratio_126", ("return", "volatility"),
        ("변동성관리", "위험예산", "volatility managed"), ("moreira_muir_volatility",),
        lookback=126, mode="scheduled_rotation", risk="defensive", priority=97,
    ),
    _r(
        "low-volatility-momentum", "momentum", "저변동 모멘텀",
        "중기 상승 중 변동성이 시장 하위 30%인 종목을 위험 대비 수익 순으로 고릅니다.",
        "R_126>0 and rank_bottom30(sigma_63); rank=R_126/sigma_126",
        "양의 126일 수익 필터와 63일 변동성 하위 횡단면 필터를 결합합니다.",
        "모멘텀의 상승 참여를 유지하면서 큰 낙폭 가능성을 낮추기 위해 씁니다.",
        (_c("return_126d", GT, 0.0), _c("realized_volatility_63d", LTE, 0.0, universe_rank_pct=.30)),
        (_c("return_21d", LT, 0.0),), "return_vol_ratio_126", ("return", "volatility"),
        ("저변동", "방어", "low volatility momentum"), ("ang_low_volatility", "jegadeesh_titman"),
        lookback=126, mode="scheduled_rotation", risk="defensive", horizon="long", priority=94,
    ),
    _r(
        "fifty-two-week-high-momentum", "momentum", "52주 신고가 근접 모멘텀",
        "현재 가격이 52주 최고가의 90% 이상이며 근접도가 상위인 종목을 고릅니다.",
        "P/High_252>=.90 and rank_top20(P/High_252)",
        "현재 종가를 252일 최고 종가로 나눈 기준점 비율을 절대 문턱과 횡단면 순위에 동시에 씁니다.",
        "과거 수익률 전체보다 투자자가 기억하는 52주 고점이라는 기준점에 대한 강도를 보기 위해 씁니다.",
        (_c("close_to_high_252", GTE, .90), _c("close_to_high_252", GTE, 0.0, universe_rank_pct=.20)),
        (_c("close_to_high_252", LT, .80),), "close_to_high_252", ("high_proximity",),
        ("52주", "신고가", "신고가 돌파", "고점근접", "52 week high"), ("george_hwang_52_week_high",),
        lookback=252, mode="scheduled_rotation", priority=96,
    ),
    _r(
        "price-volume-momentum", "momentum", "가격·거래량 모멘텀",
        "중기 상승과 평소 이상 거래량이 함께 나타난 종목을 가격·거래량 결합점수로 고릅니다.",
        "rank_top20(R_126*(.5+VR_20)) and VR_20>1",
        "126일 수익률에 거래량 배수의 절반 보정치를 곱해 점수를 만들고 평균 이상 거래량만 허용합니다.",
        "참여 없이 떠 있는 가격 상승보다 실제 거래가 동반된 추세를 우선하기 위해 씁니다.",
        (_c("price_volume_score_126", GTE, 0.0, universe_rank_pct=.20), _c("volume_ratio_20", GT, 1.0)),
        (_c("obv_slope_20", LT, 0.0),), "price_volume_score_126", ("return", "volume_ratio", "obv"),
        ("가격거래량", "거래량", "거래량모멘텀", "price volume"), ("lee_swaminathan_volume",),
        lookback=126, mode="scheduled_rotation", priority=92,
    ),
    _r(
        "rolling-sharpe-momentum", "momentum", "롤링 샤프 모멘텀",
        "126일 샤프 비율이 양수이면서 시장 상위 20%인 종목을 보유합니다.",
        "Sharpe_126>0 and rank_top20(Sharpe_126)",
        "동일한 126일 창에서 평균 일수익과 표준편차를 계산해 절대·상대 조건을 동시에 적용합니다.",
        "수익 크기보다 위험 한 단위당 보상이 꾸준했던 종목을 고르기 위해 씁니다.",
        (_c("sharpe_126", GT, 0.0), _c("sharpe_126", GTE, 0.0, universe_rank_pct=.20)),
        (_c("sharpe_42", LT, 0.0),), "sharpe_126", ("sharpe",),
        ("샤프", "위험대비", "rolling sharpe"), ("moreira_muir_volatility",),
        lookback=126, mode="scheduled_rotation", priority=90,
    ),
    _r(
        "rolling-sortino-momentum", "momentum", "롤링 소르티노 모멘텀",
        "하락 변동만 위험으로 본 126일 소르티노 점수가 상위인 종목을 고릅니다.",
        "Sortino_126>0 and rank_top20(Sortino_126)",
        "126일 평균수익을 음수 수익률의 RMS로 나눠 절대 양수와 상위 20% 조건을 적용합니다.",
        "상승 변동을 벌주지 않고 사용자가 체감하는 하방 위험 대비 성과를 보기 위해 씁니다.",
        (_c("sortino_126", GT, 0.0), _c("sortino_126", GTE, 0.0, universe_rank_pct=.20)),
        (_c("sortino_42", LT, 0.0),), "sortino_126", ("sortino",),
        ("소르티노", "하방위험", "sortino momentum"), ("quantconnect_indicators",),
        lookback=126, mode="scheduled_rotation", risk="defensive", priority=88,
    ),
    _r(
        "multi-horizon-momentum", "momentum", "다중기간 모멘텀",
        "3·6·12개월 상승을 고정 비중으로 합쳐 한 기간 급등에 덜 의존합니다.",
        "Blend=.5R_63+.3R_126+.2R_252; rank_top20(Blend); R_252>0",
        "세 기간 수익률을 사전 고정 비중으로 합산하고 장기 수익 양수와 상위 순위를 요구합니다.",
        "투자기간 표현이 모호해도 단·중·장 추세가 함께 강한 후보를 만들기 위해 씁니다.",
        (_c("momentum_blend", GTE, 0.0, universe_rank_pct=.20), _c("return_252d", GT, 0.0)),
        (_c("return_21d", LT, 0.0),), "momentum_blend", ("momentum_blend", "return"),
        ("다중기간", "3개월", "6개월", "multi horizon"), ("jegadeesh_titman", "time_series_momentum"),
        lookback=252, mode="scheduled_rotation", priority=53,
        caveat=TWO_WINDOW_BOTTOM_THIRD_CAVEAT,
    ),

    _r(
        "dual-sma-crossover", "trend", "20·50일 SMA 교차",
        "20일 평균이 50일 평균을 아래에서 위로 통과할 때 진입하고 반대 교차에서 나옵니다.",
        "buy=cross(SMA_20,SMA_50); sell=cross_down(SMA_20,SMA_50)",
        "같은 종가로 두 이동평균을 만들고 전일 관계까지 확인해 실제 교차일에만 신호를 냅니다.",
        "단순 가격 위치보다 단기 추세가 중기 추세를 추월하는 변화 시점을 잡기 위해 씁니다.",
        (_c("sma_20", CROSS_ABOVE, "sma_50"),), (_c("sma_20", CROSS_BELOW, "sma_50"),),
        "slope_20", ("sma",), ("이동평균교차", "sma crossover", "골든크로스"),
        ("brock_technical_rules", "backtrader_strategies"), lookback=50, horizon="short", priority=84,
    ),
    _r(
        "triple-sma-alignment", "trend", "삼중 SMA 정배열",
        "가격과 20·50·200일 평균이 짧은 순서대로 위에 놓인 강한 정배열만 보유합니다.",
        "P>SMA20>SMA50>SMA200; exit=P<SMA50",
        "세 시간축의 단순이동평균을 동시에 비교해 한 번의 교차보다 엄격한 추세 상태를 만듭니다.",
        "짧은 반등이 아니라 여러 기간에서 합의된 상승 추세를 찾기 위해 씁니다.",
        (_c("close", GT, "sma_20"), _c("sma_20", GT, "sma_50"), _c("sma_50", GT, "sma_200")),
        (_c("close", LT, "sma_50"),), "momentum_blend", ("sma", "momentum_blend"),
        ("정배열", "삼중이평", "triple sma"), ("faber_tactical", "brock_technical_rules"),
        lookback=200, horizon="long", priority=89,
    ),
    _r(
        "ema-crossover", "trend", "12·26일 EMA 교차",
        "최근 가격에 더 민감한 12일 EMA가 26일 EMA를 상향 돌파할 때 진입합니다.",
        "buy=cross(EMA_12,EMA_26); sell=cross_down(EMA_12,EMA_26)",
        "두 EMA를 동일한 재귀식으로 계산하고 전일과 당일의 상대 위치가 바뀐 경우만 신호로 인정합니다.",
        "SMA 교차보다 최근 전환을 빠르게 반영하는 독립 추세 신호가 필요할 때 씁니다.",
        (_c("ema_12", CROSS_ABOVE, "ema_26"),), (_c("ema_12", CROSS_BELOW, "ema_26"),),
        "slope_20", ("ema",), ("ema", "지수이평", "ema crossover"), ("talib_functions",),
        lookback=26, horizon="short", priority=78,
    ),
    _r(
        "macd-signal-crossover", "trend", "MACD 신호선 교차",
        "MACD가 9일 신호선을 상향 돌파하고 0보다 클 때 상승 가속으로 봅니다.",
        "cross(MACD,Signal) and MACD>0; exit=cross_down(MACD,Signal)",
        "12·26 EMA 차이와 그 차이의 9일 EMA를 만들고 양의 영역 교차만 사용합니다.",
        "단순 평균 교차와 달리 추세 간격의 가속을 확인하기 위해 씁니다.",
        (_c("macd", CROSS_ABOVE, "macd_signal"), _c("macd", GT, 0.0)),
        (_c("macd", CROSS_BELOW, "macd_signal"),), "macd_hist", ("macd",),
        ("macd", "신호선", "추세가속"), ("talib_functions",), lookback=35, priority=86,
    ),
    _r(
        "ppo-signal-crossover", "trend", "PPO 신호선 교차",
        "가격 수준을 보정한 EMA 간격인 PPO가 신호선을 상향 돌파할 때 진입합니다.",
        "cross(PPO,PPO_signal) and PPO>0",
        "12·26 EMA 차이를 26 EMA로 나눈 비율과 그 9일 EMA를 비교합니다.",
        "서로 가격대가 다른 종목의 추세 가속도를 같은 백분율 단위로 비교하기 위해 씁니다.",
        (_c("ppo", CROSS_ABOVE, "ppo_signal"), _c("ppo", GT, 0.0)),
        (_c("ppo", CROSS_BELOW, "ppo_signal"),), "ppo_hist", ("ppo",),
        ("ppo", "percentage price oscillator"), ("talib_functions",), lookback=35, priority=75,
    ),
    _r(
        "adx-directional-trend", "trend", "ADX 방향성 추세",
        "추세 강도 ADX가 25를 넘고 상승 방향지표가 하락 방향지표보다 클 때 진입합니다.",
        "ADX_14>25 and +DI_14>-DI_14; exit=+DI cross below -DI",
        "True Range와 방향 이동을 Wilder 평활해 강도와 방향을 분리한 뒤 다시 결합합니다.",
        "이동평균만으로 구분하기 어려운 강한 추세와 횡보를 가르기 위해 씁니다.",
        (_c("adx_14", GT, 25.0), _c("plus_di_14", GT, "minus_di_14")),
        (_c("plus_di_14", CROSS_BELOW, "minus_di_14"),), "adx_14", ("adx",),
        ("adx", "dmi", "방향지표", "강한추세"), ("talib_functions",), lookback=28, priority=87,
    ),
    _r(
        "aroon-new-high-trend", "trend", "Aroon 신고점 추세",
        "최근 고점은 매우 가깝고 최근 저점은 오래된 종목을 상승 추세로 봅니다.",
        "AroonUp_25>70 and AroonDown_25<30; exit=AroonDown>70",
        "25일 안의 최고가·최저가 발생 시점을 0~100으로 바꾸고 반대 방향 조건을 동시에 요구합니다.",
        "수익률 크기 대신 새 고점이 계속 나오는 시간 구조를 포착하기 위해 씁니다.",
        (_c("aroon_up_25", GT, 70.0), _c("aroon_down_25", LT, 30.0)),
        (_c("aroon_down_25", GT, 70.0),), "aroon_up_25", ("aroon",),
        ("aroon", "신고점시간", "아룬"), ("talib_functions",), lookback=25, priority=74,
    ),
    _r(
        "linear-regression-trend", "trend", "선형회귀 추세",
        "63일 가격선의 정규화 기울기가 양수이고 직선 설명력이 40% 이상일 때 진입합니다.",
        "slope_63>.001 and R2_63>.40; exit=slope_63<0",
        "63개 종가에 최소제곱 직선을 맞추고 기울기를 평균가격으로 나누며 잔차로 R제곱을 계산합니다.",
        "한두 번 급등보다 방향이 일정한 추세를 선호하기 위해 씁니다.",
        (_c("slope_63", GT, .001), _c("r_squared_63", GT, .40)), (_c("slope_63", LT, 0.0),),
        "slope_63", ("slope",), ("선형회귀", "기울기", "linear regression"),
        ("talib_functions",), lookback=63, priority=81,
    ),
    _r(
        "kaufman-efficient-trend", "trend", "Kaufman 효율 추세",
        "20일 순상승이 5%를 넘고 이동 효율이 0.3 이상인 매끄러운 추세만 고릅니다.",
        "ER_20>.30 and R_20>.05; exit=R_10<0",
        "순변화/총이동거리 효율비율과 기간 수익률을 결합해 방향과 매끄러움을 동시에 요구합니다.",
        "같은 5% 상승이라도 심하게 왕복한 종목보다 직선적으로 오른 종목을 찾기 위해 씁니다.",
        (_c("efficiency_ratio_20", GT, .30), _c("return_20d", GT, .05)), (_c("return_10d", LT, 0.0),),
        "efficiency_ratio_20", ("efficiency", "return"), ("효율비율", "kaufman", "매끄러운추세"),
        ("quantconnect_indicators",), lookback=20, priority=82,
    ),
    _r(
        "trix-smoothed-trend", "trend", "TRIX 평활 추세",
        "세 번 평활한 변화율 TRIX가 자기 신호선을 위로 통과할 때 진입합니다.",
        "cross(TRIX_15,EMA9(TRIX)); exit=cross_down",
        "15일 EMA를 세 번 적용한 값의 변화율과 그 변화율의 9일 EMA를 비교합니다.",
        "거친 단기 잡음을 크게 줄인 별도의 장기 추세 전환 신호가 필요할 때 씁니다.",
        (_c("trix_15", CROSS_ABOVE, "trix_signal_9"),), (_c("trix_15", CROSS_BELOW, "trix_signal_9"),),
        "trix_15", ("trix",), ("trix", "삼중평활"), ("talib_functions",), lookback=55, horizon="long", priority=69,
    ),
    _r(
        "supertrend-atr-state", "trend", "Supertrend ATR 상태",
        "가격 변동폭에 맞춰 움직이는 Supertrend 선이 상승 상태일 때 보유합니다.",
        "direction(Supertrend_10,3)=+1; exit=-1",
        "중간가격±3ATR 밴드를 전일 상태와 연결해 상승/하락 상태를 재귀적으로 계산합니다.",
        "고정 이동평균보다 종목별 변동성에 적응하는 추적 추세선을 쓰기 위해 선택했습니다.",
        (_c("supertrend_direction_10_3", GTE, 1.0),), (_c("supertrend_direction_10_3", LTE, -1.0),),
        "return_63d", ("supertrend", "atr"), ("supertrend", "atr추세", "추적선"),
        ("quantconnect_indicators",), lookback=30, priority=91,
    ),

    _r(
        "donchian-price-breakout", "breakout", "Donchian 고점 돌파",
        "종가가 오늘을 제외한 직전 20일 최고가를 처음 넘을 때 진입합니다.",
        "cross(P,DonchianHigh_20); exit=P<SMA_20",
        "직전 고가의 20일 최댓값을 만들고 전일에는 아래, 오늘은 위인 실제 교차만 인정합니다.",
        "고전적 거래범위 돌파를 자기참조 없이 가장 단순하게 실행하기 위해 씁니다.",
        (_c("close", CROSS_ABOVE, "donchian_high_20"),), (_c("close", LT, "sma_20"),),
        "atr_expansion_20", ("donchian", "sma"), ("donchian", "돌파", "20일고점", "가격돌파"),
        ("brock_technical_rules",), lookback=20, risk="aggressive", horizon="short", priority=50,
        caveat=TWO_WINDOW_BOTTOM_THIRD_CAVEAT,
    ),
    _r(
        "bollinger-volatility-breakout", "breakout", "볼린저 상단 돌파",
        "종가가 자체 변동성을 반영한 볼린저 상단을 처음 넘을 때 진입합니다.",
        "cross(P,BBUpper_20); exit=P<BBMiddle_20",
        "20일 평균과 표준편차 두 배로 상단을 만들고 전일·당일 교차를 확인합니다.",
        "고정 고점보다 최근 변동성에 맞춘 이례적 상승을 포착하기 위해 씁니다.",
        (_c("close", CROSS_ABOVE, "bollinger_upper_20"),), (_c("close", LT, "bollinger_middle_20"),),
        "bollinger_pct_20", ("bollinger",), ("볼린저", "돌파", "상단돌파", "bollinger breakout"),
        ("talib_functions",), lookback=20, risk="aggressive", horizon="short", priority=79,
    ),
    _r(
        "keltner-atr-breakout", "breakout", "Keltner ATR 돌파",
        "종가가 EMA에서 2ATR 위에 있는 Keltner 상단을 돌파할 때 진입합니다.",
        "cross(P,EMA_20+2ATR_10); exit=P<EMA_20",
        "20일 EMA에 갭 포함 10일 ATR 두 배를 더한 동적 상단을 계산합니다.",
        "표준편차 대신 실제 거래 범위를 쓰는 독립적인 변동성 돌파를 만들기 위해 씁니다.",
        (_c("close", CROSS_ABOVE, "keltner_upper_20"),), (_c("close", LT, "ema_20"),),
        "atr_expansion_20", ("keltner", "atr", "ema"), ("keltner", "켈트너", "돌파", "atr돌파"),
        ("quantconnect_indicators",), lookback=30, risk="aggressive", horizon="short", priority=78,
    ),
    _r(
        "atr-range-expansion-breakout", "breakout", "ATR 범위확장 돌파",
        "직전 고점을 넘으면서 당일 실제 범위가 평소 ATR의 1.2배 이상일 때만 진입합니다.",
        "P>DonchianHigh_20 and TR/ATR_20>1.2",
        "직전 20일 고점 조건에 True Range/ATR 비율 조건을 붙여 작은 돌파를 제외합니다.",
        "거래 가능한 큰 방향 움직임과 미세한 고점 갱신을 구분하기 위해 씁니다.",
        (_c("close", GT, "donchian_high_20"), _c("atr_expansion_20", GT, 1.2)),
        (_c("close", LT, "atr_trailing_floor_20"),), "atr_expansion_20", ("donchian", "atr", "range_expansion"),
        ("atr확장", "돌파", "범위돌파", "range expansion"), ("talib_functions",),
        lookback=20, risk="aggressive", horizon="short", priority=88,
    ),
    _r(
        "bollinger-squeeze-breakout", "breakout", "볼린저 스퀴즈 돌파",
        "20일 밴드 폭이 장기 평소 폭의 60% 아래로 압축된 뒤 20일 고점을 넘으면 진입합니다.",
        "BBWidth_20<.6*avg120(BBWidth_20) and P>High_20",
        "밴드 폭의 절대값이 아니라 자기 120일 평균 대비 비율과 직전 고점 돌파를 결합합니다.",
        "조용한 압축 구간 뒤 시작되는 큰 움직임 후보를 선별하기 위해 씁니다.",
        (_c("squeeze_breakout", GT, .5),), (_c("close", LT, "sma_20"),),
        "atr_expansion_20", ("squeeze", "bollinger", "donchian"), ("스퀴즈", "변동성압축", "squeeze breakout"),
        ("quantconnect_indicators",), lookback=140, risk="aggressive", priority=85,
    ),
    _r(
        "nr7-compression-breakout", "breakout", "NR7 압축 돌파",
        "전일 범위가 7일 중 가장 좁았고 오늘 종가가 전일 고점을 넘을 때 진입합니다.",
        "Range_{t-1}=min7 and P_t>H_{t-1}",
        "전일 고저 폭을 그 이전 7개 폭과 비교한 후 다음 봉 종가 돌파를 요구합니다.",
        "밴드 지표와 다른 순수 봉 범위 기반 압축 신호를 추가하기 위해 씁니다.",
        (_c("nr7_breakout", GT, .5),), (_c("close", LT, "sma_10"),),
        "atr_expansion_20", ("nr7", "candle_pattern"), ("nr7", "좁은봉", "압축돌파"),
        ("lean_engine",), lookback=10, risk="aggressive", horizon="short", priority=26,
        caveat=TWO_WINDOW_BOTTOM_THIRD_CAVEAT,
    ),
    _r(
        "inside-bar-breakout", "breakout", "Inside Bar 돌파",
        "전일 봉이 그 전 봉 안에 완전히 들어온 뒤 오늘 종가가 전일 고점을 넘으면 진입합니다.",
        "Inside_{t-1} and P_t>H_{t-1}",
        "두 이전 봉의 고저 포함관계를 확인하고 현재 종가 돌파를 별도 단계로 계산합니다.",
        "짧은 가격 압축을 이동평균 없이 OHLC 구조만으로 포착하기 위해 씁니다.",
        (_c("inside_bar_breakout", GT, .5),), (_c("close", LT, "sma_10"),),
        "atr_expansion_20", ("candle_pattern",), ("inside bar", "인사이드바", "봉압축"),
        ("lean_engine",), lookback=10, risk="aggressive", horizon="short", priority=24,
        caveat=TWO_WINDOW_BOTTOM_THIRD_CAVEAT,
    ),
    _r(
        "outside-bar-continuation", "breakout", "Outside Bar 상승 지속",
        "당일 봉이 전일 고저를 모두 감싸고 시가보다 높게 마감하면 상승 확장으로 봅니다.",
        "H_t>H_{t-1} and L_t<L_{t-1} and C_t>O_t",
        "고가·저가 포함관계와 양봉 여부를 같은 현재 봉에서 확인하고 다음 시가에만 체결합니다.",
        "압축 돌파와 반대인 강한 범위 확장형 지속 패턴도 독립 후보로 비교하기 위해 씁니다.",
        (_c("outside_bar_continuation", GT, .5),), (_c("close", LT, "ema_20"),),
        "atr_expansion_20", ("candle_pattern", "range_expansion"), ("outside bar", "아웃사이드바", "범위확장"),
        ("lean_engine",), lookback=20, risk="aggressive", horizon="short", priority=21,
        caveat=TWO_WINDOW_BOTTOM_THIRD_CAVEAT,
    ),
    _r(
        "gap-up-volume-breakout", "breakout", "갭상승·거래량 돌파",
        "2% 이상 갭상승 후 양봉으로 마감하고 거래량이 평균의 1.5배 이상일 때 진입합니다.",
        "Gap>2%, C>O, VR_20>1.5",
        "시가/전일종가 갭, 당일 마감 방향, 20일 거래량 배수를 모두 충족해야 1로 표시합니다.",
        "밤사이 정보 충격이 실제 장중 수요로 이어졌는지 확인하기 위해 씁니다.",
        (_c("gap_up_volume_breakout", GT, .5),), (_c("return_5d", LT, -.05),),
        "price_volume_score_20", ("gap", "volume_ratio"), ("갭상승", "거래량", "돌파", "거래량돌파", "gap breakout"),
        ("lean_engine", "lee_swaminathan_volume"), lookback=20, risk="aggressive", horizon="short", priority=72,
    ),
    _r(
        "wide-range-close-breakout", "breakout", "Wide Range 상단마감 돌파",
        "실제 범위가 20일 ATR의 1.5배 이상이고 종가가 봉 상단 20% 안에서 고점을 돌파할 때 진입합니다.",
        "TR/ATR_20>1.5 and close_location>.8 and P>High_20",
        "갭 포함 범위 배수, 봉 안 종가 위치, 직전 고점 돌파를 하나의 재현 가능한 플래그로 계산합니다.",
        "크기만 큰 양방향 봉이 아니라 매수세가 끝까지 유지된 확장봉을 찾기 위해 씁니다.",
        (_c("range_expansion_breakout", GT, .5),), (_c("close", LT, "sma_20"),),
        "atr_expansion_20", ("range_expansion", "atr", "donchian"), ("wide range", "상단마감", "확장봉"),
        ("talib_functions",), lookback=20, risk="aggressive", horizon="short", priority=36,
        caveat=TWO_WINDOW_BOTTOM_THIRD_CAVEAT,
    ),
    _r(
        "high-tight-flag-breakout", "breakout", "High Tight Flag",
        "20일 15% 이상 상승 뒤 고점 3% 안에서 낮은 변동성으로 버티는 종목을 고릅니다.",
        "R_20>.15 and P/High_20>.97 and sigma_10<25%",
        "단기 급등, 고점 근접도, 이후 변동성 축소를 동시에 요구해 단순 신고가와 구분합니다.",
        "큰 상승을 되돌리지 않고 좁게 소화하는 강한 수급 구조를 찾기 위해 씁니다.",
        (_c("return_20d", GT, .15), _c("close_to_high_20", GT, .97), _c("realized_volatility_10d", LT, .25)),
        (_c("close_to_high_20", LT, .90),), "return_vol_ratio_20", ("return", "high_proximity", "volatility"),
        ("high tight flag", "고점횡보", "타이트플래그"), ("lean_engine",),
        lookback=20, risk="aggressive", horizon="short", priority=70,
    ),

    _r(
        "rsi-oversold-reversion", "mean_reversion", "RSI 과매도 반전",
        "14일 RSI가 30 이하일 때 과도한 단기 하락으로 보고 반등 후보에 넣습니다.",
        "buy=RSI_14<=30; exit=RSI_14>=55",
        "Wilder 방식으로 상승·하락 평균을 만든 뒤 0~100 RSI 문턱을 사전에 고정합니다.",
        "가격 수준과 무관하게 단기 매도 압력이 극단에 이른 후보를 찾기 위해 씁니다.",
        (_c("rsi_14", LTE, 30.0),), (_c("rsi_14", GTE, 55.0),), "price_zscore_20", ("rsi",),
        ("rsi", "과매도", "반등"), ("talib_functions",), lookback=14, risk="aggressive", horizon="short", priority=73,
        caveat="강한 하락 추세에서는 RSI가 오래 과매도에 머물 수 있습니다.",
    ),
    _r(
        "bollinger-lower-band-reentry", "mean_reversion", "볼린저 하단 재진입",
        "종가가 볼린저 하단 아래에서 다시 위로 들어올 때 반등 확인 후 진입합니다.",
        "cross_up(P,BBLower_20); exit=P>=BBMiddle_20",
        "전일에는 하단 이하, 당일에는 하단 위인지 확인해 단순 하단 접촉보다 한 단계 확인합니다.",
        "떨어지는 중 바로 사지 않고 통계적 범위 안으로 복귀한 시점을 쓰기 위해 씁니다.",
        (_c("close", CROSS_ABOVE, "bollinger_lower_20"),), (_c("close", GTE, "bollinger_middle_20"),),
        "price_zscore_20", ("bollinger", "zscore"), ("볼린저하단", "재진입", "lower band reentry"),
        ("talib_functions",), lookback=20, horizon="short", priority=80,
    ),
    _r(
        "price-zscore-reversion", "mean_reversion", "가격 Z점수 회귀",
        "가격이 20일 평균보다 2표준편차 아래일 때 진입하고 평균에 돌아오면 나옵니다.",
        "Z_20<=-2; exit=Z_20>=0",
        "20일 평균과 표준편차로 종가 이탈을 표준화하고 0을 평균 복귀 지점으로 둡니다.",
        "서로 다른 가격·변동성 종목의 과도한 이탈을 같은 척도로 비교하기 위해 씁니다.",
        (_c("price_zscore_20", LTE, -2.0),), (_c("price_zscore_20", GTE, 0.0),),
        "price_zscore_20", ("zscore",), ("zscore", "표준점수", "평균회귀"),
        ("quantconnect_indicators",), lookback=20, horizon="short", priority=77,
    ),
    _r(
        "stochastic-oversold-crossover", "mean_reversion", "스토캐스틱 과매도 교차",
        "%K가 25 이하에서 %D를 상향 돌파할 때 범위 하단 반등으로 봅니다.",
        "%K_14 cross above %D_3 and %K<=25; exit=%K>=80",
        "14일 고저 범위의 종가 위치와 그 3일 평균을 계산하고 과매도 영역의 교차만 허용합니다.",
        "박스권 하단에서 방향이 실제로 위로 바뀐 시점을 확인하기 위해 씁니다.",
        (_c("stoch_k_14", CROSS_ABOVE, "stoch_d_3"), _c("stoch_k_14", LTE, 25.0)),
        (_c("stoch_k_14", GTE, 80.0),), "stoch_k_14", ("stochastic",),
        ("스토캐스틱", "stochastic", "%k"), ("talib_functions",), lookback=16, horizon="short", priority=68,
    ),
    _r(
        "williams-r-reversal", "mean_reversion", "Williams %R 반전",
        "%R가 -80 아래인 고저 범위 극단에서 진입하고 -20 위에서 청산합니다.",
        "%R_14<=-80; exit=%R_14>=-20",
        "14일 최고·최저 대비 종가 거리를 -100~0으로 변환해 양끝 문턱을 고정합니다.",
        "RSI와 산식이 다른 가격 범위 기반 과매도 신호를 독립 비교하기 위해 씁니다.",
        (_c("williams_r_14", LTE, -80.0),), (_c("williams_r_14", GTE, -20.0),),
        "williams_r_14", ("williams_r",), ("williams", "%r", "윌리엄스"),
        ("talib_functions",), lookback=14, horizon="short", priority=59,
    ),
    _r(
        "cci-cycle-reversal", "mean_reversion", "CCI 순환 반전",
        "20일 CCI가 -100 아래일 때 진입하고 +100 위에서 과열 청산합니다.",
        "CCI_20<=-100; exit=CCI_20>=100",
        "전형가격의 평균 이탈을 평균절대편차로 나눠 고정된 순환 문턱을 적용합니다.",
        "표준편차가 아닌 절대편차 기반의 독립적인 평균회귀 후보를 만들기 위해 씁니다.",
        (_c("cci_20", LTE, -100.0),), (_c("cci_20", GTE, 100.0),), "cci_20", ("cci",),
        ("cci", "commodity channel", "순환반전"), ("talib_functions",), lookback=20, horizon="short", priority=57,
    ),
    _r(
        "mfi-oversold-reversal", "mean_reversion", "MFI 자금흐름 반전",
        "가격과 거래량을 함께 본 MFI가 20 이하일 때 진입하고 80 이상에서 나옵니다.",
        "MFI_14<=20; exit=MFI_14>=80",
        "전형가격×거래량의 14일 양·음 흐름 비율을 0~100으로 바꿔 양끝 문턱을 적용합니다.",
        "가격 과매도에 실제 자금 흐름 정보까지 포함한 별도 반전 신호가 필요해 씁니다.",
        (_c("mfi_14", LTE, 20.0),), (_c("mfi_14", GTE, 80.0),), "mfi_14", ("mfi",),
        ("mfi", "자금흐름", "거래량과매도"), ("talib_functions",), lookback=14, horizon="short", priority=65,
    ),
    _r(
        "short-term-cross-sectional-reversal", "mean_reversion", "단기 횡단면 반전",
        "최근 5일 수익률이 시장 하위 10%인 종목을 고르고 5일 수익이 회복되면 나옵니다.",
        "rank_bottom10(R_5); exit=R_5>=0",
        "같은 날 전 종목의 5일 수익률을 낮은 순서로 정렬해 하위 10%만 순환 보유합니다.",
        "시장 공통 충격보다 상대적으로 과도하게 팔린 종목의 단기 되돌림을 노리기 위해 씁니다.",
        (_c("return_5d", LTE, 0.0, universe_rank_pct=.10),), (_c("return_5d", GTE, 0.0),),
        "return_5d", ("return", "relative_strength"), ("단기반전", "횡단면반전", "short reversal"),
        ("jegadeesh_titman",), lookback=5, direction="asc", mode="scheduled_rotation", risk="aggressive", horizon="short", priority=71,
    ),
    _r(
        "gap-down-reversal", "mean_reversion", "갭하락 반전",
        "전일 종가보다 3% 이상 낮게 시작한 충격을 단기 과잉반응 후보로 봅니다.",
        "Gap<=-3%; exit=R_3>0",
        "당일 시가/전일 종가 수익률로 밤사이 충격을 분리하고 이후 3일 수익 양수에서 청산합니다.",
        "장중 하락과 다른 정보 충격성 갭의 되돌림을 별도 전략으로 비교하기 위해 씁니다.",
        (_c("gap_pct", LTE, -.03),), (_c("return_3d", GT, 0.0),), "gap_pct", ("gap",),
        ("갭하락", "gap down", "과잉반응"), ("lean_engine",), lookback=5, direction="asc", risk="aggressive", horizon="short", priority=55,
    ),
    _r(
        "vwap-deviation-reversion", "mean_reversion", "VWAP 이탈 회귀",
        "종가가 20일 거래량가중 평균가격보다 5% 아래면 진입하고 평균원가에 돌아오면 나옵니다.",
        "P/VWAP_20<=.95; exit=P/VWAP_20>=1",
        "전형가격에 거래량을 가중한 20일 평균을 만들고 현재 종가의 비율을 계산합니다.",
        "단순 평균보다 실제 거래가 많이 된 시장 참여자의 원가를 회귀 기준으로 삼기 위해 씁니다.",
        (_c("close_to_vwap_20", LTE, .95),), (_c("close_to_vwap_20", GTE, 1.0),),
        "close_to_vwap_20", ("vwap",), ("vwap", "거래량가중평균", "원가회귀"),
        ("quantconnect_indicators",), lookback=20, horizon="short", priority=63,
    ),
    _r(
        "volume-climax-reversal", "mean_reversion", "거래량 클라이맥스 반전",
        "평균 두 배 이상 거래량과 RSI 35 이하가 겹친 투매 후보에 진입합니다.",
        "VR_20>=2 and RSI_14<=35; exit=RSI>=55",
        "20일 평균 거래량 배수와 Wilder RSI를 결합해 가격 하락만 있는 경우를 제외합니다.",
        "실제 대량 손바뀜이 동반된 과매도에서 매도 압력 소진 가능성을 보기 위해 씁니다.",
        (_c("volume_ratio_20", GTE, 2.0), _c("rsi_14", LTE, 35.0)), (_c("rsi_14", GTE, 55.0),),
        "volume_ratio_20", ("volume_ratio", "rsi"), ("거래량클라이맥스", "거래량", "투매", "volume climax"),
        ("lee_swaminathan_volume", "talib_functions"), lookback=20, risk="aggressive", horizon="short", priority=62,
    ),
    _r(
        "consecutive-loss-reversal", "mean_reversion", "연속 하락 반전",
        "3일 이상 연속 하락하고 RSI도 40 이하인 종목을 누적 매도 압력 후보로 봅니다.",
        "LossStreak>=3 and RSI<=40; exit=R_5>0",
        "전일 대비 종가 하락 연속 횟수와 RSI 조건을 결합해 단발 급락과 구분합니다.",
        "며칠에 걸친 매도 쏠림이 정상화되는 단기 반전을 찾기 위해 씁니다.",
        (_c("loss_streak", GTE, 3.0), _c("rsi_14", LTE, 40.0)), (_c("return_5d", GT, 0.0),),
        "loss_streak", ("loss_streak", "rsi"), ("연속하락", "loss streak", "반전"),
        ("lean_engine", "talib_functions"), lookback=14, risk="aggressive", horizon="short", priority=58,
    ),

    _r(
        "obv-accumulation-trend", "volume_flow", "OBV 누적수급 추세",
        "OBV의 20일 기울기가 양수이고 가격도 50일 평균 위일 때 매집 추세로 봅니다.",
        "slope20(OBV)>0 and P>SMA_50",
        "상승·하락일 거래량 누적선에 20일 회귀 기울기를 적용하고 가격 추세로 확인합니다.",
        "가격보다 먼저 움직일 수 있는 누적 참여 방향을 추세 필터와 함께 보기 위해 씁니다.",
        (_c("obv_slope_20", GT, 0.0), _c("close", GT, "sma_50")),
        (_c("obv_slope_20", LT, 0.0),), "obv_slope_20", ("obv", "sma"),
        ("obv", "누적거래량", "매집"), ("talib_functions",), lookback=50, priority=75,
    ),
    _r(
        "chaikin-money-flow-trend", "volume_flow", "Chaikin Money Flow 추세",
        "20일 CMF가 0.1보다 크고 가격 수익도 양수일 때 지속 매수 압력으로 봅니다.",
        "CMF_20>.10 and R_20>0; exit=CMF<0",
        "봉 내 종가 위치×거래량의 20일 합을 거래량 합으로 나누고 가격 방향 조건을 더합니다.",
        "단순 거래량 증가가 매수인지 매도인지 종가 위치로 구분하기 위해 씁니다.",
        (_c("cmf_20", GT, .10), _c("return_20d", GT, 0.0)), (_c("cmf_20", LT, 0.0),),
        "cmf_20", ("cmf", "return"), ("cmf", "chaikin", "자금흐름"),
        ("quantconnect_indicators",), lookback=20, priority=76,
    ),
    _r(
        "accumulation-distribution-trend", "volume_flow", "A/D Line 매집 추세",
        "A/D 누적선의 20일 기울기가 양수이고 가격이 EMA 위일 때 매집으로 봅니다.",
        "slope20(ADL)>0 and P>EMA_20",
        "일별 자금흐름량을 누적한 뒤 회귀 기울기와 20일 EMA 가격 필터를 결합합니다.",
        "CMF의 창 합계와 다른 누적 수급의 장기 방향을 독립적으로 비교하기 위해 씁니다.",
        (_c("adl_slope_20", GT, 0.0), _c("close", GT, "ema_20")),
        (_c("adl_slope_20", LT, 0.0),), "adl_slope_20", ("adl", "ema"),
        ("adl", "accumulation distribution", "매집분산"), ("talib_functions",), lookback=20, priority=70,
    ),
    _r(
        "positive-volume-index-trend", "volume_flow", "PVI 활발한 참여 추세",
        "거래량 증가일 수익만 누적한 PVI가 자기 100일 평균 위에 있을 때 보유합니다.",
        "PVI>PVI_SMA100; exit=PVI<PVI_SMA100",
        "1000에서 시작한 PVI를 거래량 증가일에만 갱신하고 그 누적선의 100일 평균과 비교합니다.",
        "활발한 거래가 발생한 날의 가격 방향이 장기적으로 우호적인지 보기 위해 씁니다.",
        (_c("pvi", GT, "pvi_sma_100"),), (_c("pvi", LT, "pvi_sma_100"),),
        "pvi_trend_gap", ("pvi",), ("pvi", "positive volume index", "활발한거래"),
        ("quantconnect_indicators",), lookback=100, horizon="long", priority=20,
        caveat=TWO_WINDOW_BOTTOM_THIRD_CAVEAT,
    ),
    _r(
        "negative-volume-index-trend", "volume_flow", "NVI 조용한 참여 추세",
        "거래량 감소일 수익만 누적한 NVI가 자기 100일 평균 위에 있을 때 보유합니다.",
        "NVI>NVI_SMA100; exit=NVI<NVI_SMA100",
        "1000에서 시작한 NVI를 거래량 감소일에만 갱신하고 100일 평균과 비교합니다.",
        "거래 소음이 적은 날에도 유지되는 가격 방향을 별도 수급 추세로 보기 위해 씁니다.",
        (_c("nvi", GT, "nvi_sma_100"),), (_c("nvi", LT, "nvi_sma_100"),),
        "nvi_trend_gap", ("nvi",), ("nvi", "negative volume index", "조용한거래"),
        ("quantconnect_indicators",), lookback=100, horizon="long", priority=64,
    ),
    _r(
        "force-index-trend", "volume_flow", "Force Index 추세",
        "가격 변화×거래량의 13일 EMA가 양수이고 가격도 20일 EMA 위일 때 진입합니다.",
        "EMA13((C-Cprev)*V)>0 and P>EMA20",
        "일별 가격 변화액에 거래량을 곱한 뒤 13일 EMA로 평활해 가격 추세와 결합합니다.",
        "상승폭뿐 아니라 그 움직임을 만든 거래 힘의 크기를 반영하기 위해 씁니다.",
        (_c("force_index_13", GT, 0.0), _c("close", GT, "ema_20")),
        (_c("force_index_13", LT, 0.0),), "force_index_13", ("force_index", "ema"),
        ("force index", "포스인덱스", "가격거래힘"), ("quantconnect_indicators",), lookback=20, priority=27,
        caveat=TWO_WINDOW_BOTTOM_THIRD_CAVEAT,
    ),
    _r(
        "ease-of-movement-trend", "volume_flow", "Ease of Movement 추세",
        "14일 EOM이 양수이고 20일 수익도 양수일 때 적은 저항의 상승으로 봅니다.",
        "EOM_14>0 and R_20>0; exit=EOM<0",
        "고저 중간값 이동과 봉 폭을 거래량으로 조정해 14일 평균하고 가격 방향을 확인합니다.",
        "큰 거래량을 계속 요구하지 않고 가격이 얼마나 쉽게 움직였는지를 보기 위해 씁니다.",
        (_c("eom_14", GT, 0.0), _c("return_20d", GT, 0.0)), (_c("eom_14", LT, 0.0),),
        "eom_14", ("eom", "return"), ("ease of movement", "eom", "이동용이성"),
        ("quantconnect_indicators",), lookback=20, priority=16,
        caveat=TWO_WINDOW_BOTTOM_THIRD_CAVEAT,
    ),
    _r(
        "percentage-volume-oscillator", "volume_flow", "PVO 거래 참여 가속",
        "단기 거래량 EMA가 장기 EMA를 비율상 추월하고 PVO가 양수일 때 진입합니다.",
        "cross(PVO,PVO_signal) and PVO>0",
        "12·26일 거래량 EMA 차이를 비율화하고 그 9일 EMA 신호선과 교차를 확인합니다.",
        "가격 신호 없이도 시장 참여가 빨라지는 시점을 독립 후보로 만들기 위해 씁니다.",
        (_c("pvo", CROSS_ABOVE, "pvo_signal"), _c("pvo", GT, 0.0)), (_c("pvo", CROSS_BELOW, "pvo_signal"),),
        "pvo_hist", ("pvo",), ("pvo", "거래량", "거래량오실레이터", "참여가속"),
        ("talib_functions",), lookback=35, horizon="short", priority=62,
    ),
    _r(
        "pure-low-volatility-trend", "defensive", "순수 저변동 추세",
        "63일 변동성이 시장 하위 20%이면서 200일 평균 위인 종목을 방어적으로 순환 보유합니다.",
        "rank_bottom20(sigma_63) and P>SMA200",
        "연율 63일 변동성 횡단면 하위군에 장기 가격 추세 필터를 적용합니다.",
        "낮은 위험 자체를 핵심 신호로 두되 장기 하락 종목을 피하기 위해 씁니다.",
        (_c("realized_volatility_63d", LTE, 0.0, universe_rank_pct=.20), _c("close", GT, "sma_200")),
        (_c("close", LT, "sma_200"),), "realized_volatility_63d", ("volatility", "sma"),
        ("순수저변동", "low volatility", "방어"), ("ang_low_volatility",),
        lookback=200, direction="asc", mode="scheduled_rotation", risk="defensive", horizon="long", priority=91,
    ),
    _r(
        "ulcer-index-trend", "defensive", "Ulcer Index 방어 추세",
        "고점 아래에서 받은 손실 스트레스가 시장 하위 25%이고 중기 수익이 양수인 종목을 고릅니다.",
        "rank_bottom25(UI_63) and R_126>0; exit=UI_63>20",
        "63일 고점대비 하락률 제곱평균의 제곱근을 순위화하고 126일 양의 수익을 확인합니다.",
        "상승 변동은 벌주지 않고 오래 지속되는 하락 스트레스가 적은 종목을 고르기 위해 씁니다.",
        (_c("ulcer_index_63", LTE, 0.0, universe_rank_pct=.25), _c("return_126d", GT, 0.0)),
        (_c("ulcer_index_63", GT, 20.0),), "ulcer_index_63", ("ulcer", "return"),
        ("ulcer index", "하락스트레스", "방어추세"), ("quantconnect_indicators",),
        lookback=126, direction="asc", mode="scheduled_rotation", risk="defensive", horizon="long", priority=83,
    ),
    _r(
        "drawdown-recovery", "defensive", "낙폭 회복 추세",
        "최근 낙폭에 비해 20일 반등 힘이 충분히 큰 종목만 회복 후보로 고릅니다.",
        "Recovery=R_20/abs(DD_63)>.5; exit=DD_63<-15%",
        "63일 고점대비 낙폭의 절댓값으로 20일 수익률을 나눠 단순 저가와 실제 회복을 구분합니다.",
        "싸 보이기만 하는 하락 종목 대신 반등 힘이 이미 확인된 회복 국면을 찾기 위해 씁니다.",
        (_c("drawdown_recovery_63", GT, .5),), (_c("drawdown_63", LT, -.15),),
        "drawdown_recovery_63", ("drawdown", "return"), ("낙폭회복", "drawdown recovery", "회복추세"),
        ("quantconnect_indicators",), lookback=63, risk="defensive", priority=74,
    ),

    # ---- Fundamental factor & multi-factor rows (beyond price-only technicals) ----
    # These use the point-in-time DART fundamentals the loader forward-fills onto every
    # bar (per/roe/operating_margin/debt_to_equity and the {metric}_up_streak columns),
    # combined with cross-sectional rank cuts and a price-trend exit.  Priorities are kept
    # below the top technical momentum rows so they do not displace the existing default
    # selection for generic requests; they surface when a request names value/quality/etc.
    _r(
        "earnings-value-quality-rotation", "value_quality", "저평가+수익성 로테이션",
        "PER이 시장에서 싼 하위 40%이면서 ROE가 양수인 흑자 우량주만 골라, 그중 ROE가 높은 순으로 순환 보유합니다.",
        "rank_bottom40(PER) and ROE>0; rank=ROE desc",
        "적자기업은 PER이 비어 자동 제외되고, 남은 흑자기업 중 PER 하위 40% 저평가 종목을 ROE 높은 순으로 보유해 싼값과 수익성을 함께 요구합니다.",
        "가격지표만으로는 볼 수 없는 이익 대비 저평가와 자본수익성을 결합해 밸류트랩을 피하려고 씁니다(그린블랫 매직포뮬러 적응형).",
        (_c("per", LTE, 0.0, universe_rank_pct=.40), _c("roe", GT, 0.0)),
        (_c("close", LT, "sma_200"),), "roe", ("per", "roe"),
        ("밸류", "저평가", "per", "저per", "수익성", "매직포뮬러", "value", "quality"),
        ("greenblatt_magic_formula",),
        lookback=200, direction="desc", mode="scheduled_rotation", risk="balanced", horizon="long", priority=62,
        caveat="지주사·재벌계열은 지분법이익·일회성 이익으로 PER이 왜곡될 수 있어 ROE 품질 필터를 함께 씁니다.",
    ),
    _r(
        "profitability-quality-leaders", "quality", "수익성 우량주 리더",
        "영업이익률이 시장 상위 30%이면서 ROE가 양수인 고수익성 기업을 영업이익률 높은 순으로 순환 보유합니다.",
        "rank_top30(operating_margin) and ROE>0; rank=operating_margin desc",
        "본업 마진이 상위 30%인 기업에 흑자 조건을 더해, 마진이 높은 순으로 보유합니다.",
        "가격 추세가 아니라 사업 자체의 마진 경쟁력으로 종목을 고르기 위해 씁니다(Novy-Marx 수익성 프리미엄 적응형).",
        (_c("operating_margin", GTE, 0.0, universe_rank_pct=.30), _c("roe", GT, 0.0)),
        (_c("close", LT, "sma_200"),), "operating_margin", ("operating_margin", "roe"),
        ("수익성", "우량주", "영업이익률", "마진", "quality", "profitability"),
        ("novy_marx_profitability",),
        lookback=200, direction="desc", mode="scheduled_rotation", risk="defensive", horizon="long", priority=60,
        caveat="영업이익률은 Novy-Marx의 총이익/자산과 달라 자산집약 업종을 낮게 평가할 수 있습니다.",
    ),
    _r(
        "quality-minus-junk-composite", "quality", "퀄리티-정크 복합",
        "ROE가 상위 40%로 높으면서 부채비율은 하위 50%로 낮은 고품질·저위험 기업을 ROE 높은 순으로 보유합니다.",
        "rank_top40(ROE) and rank_bottom50(D/E); rank=ROE desc",
        "수익성(ROE 상위)과 안전성(부채비율 하위)을 동시에 요구해 이익은 나지만 빚으로 떠받친 기업을 걸러냅니다.",
        "고수익성과 저레버리지를 결합한 '우량(quality)' 정의로 정크를 배제하기 위해 씁니다(Asness-Frazzini-Pedersen QMJ 적응형).",
        (_c("roe", GTE, 0.0, universe_rank_pct=.40), _c("debt_to_equity", LTE, 0.0, universe_rank_pct=.50)),
        (_c("close", LT, "sma_200"),), "roe", ("roe", "debt_to_equity"),
        ("퀄리티", "우량", "저부채", "안전성", "qmj", "quality", "quality minus junk"),
        ("asness_frazzini_pedersen_qmj",),
        lookback=200, direction="desc", mode="scheduled_rotation", risk="balanced", horizon="medium", priority=58,
        caveat="분기 재무는 공시 지연이 있어 최신 자본구조 변화가 며칠 늦게 반영될 수 있습니다.",
    ),
    _r(
        "low-vol-quality-defensive", "defensive_quality", "저변동 우량주",
        "실현변동성이 시장 하위 40%로 안정적이면서 ROE가 양수인 흑자 기업을 변동성이 낮은 순으로 방어적으로 보유합니다.",
        "rank_bottom40(sigma_63) and ROE>0; rank=sigma_63 asc",
        "63일 실현변동성 하위 40% 필터에 흑자 조건을 더해, 가장 덜 흔들리는 순으로 보유합니다.",
        "낮은 위험과 사업 수익성을 결합해 하락장 방어력이 큰 우량주를 고르기 위해 씁니다(저베타·퀄리티 결합).",
        (_c("realized_volatility_63d", LTE, 0.0, universe_rank_pct=.40), _c("roe", GT, 0.0)),
        (_c("close", LT, "sma_200"),), "realized_volatility_63d", ("volatility", "roe"),
        # Tags deliberately avoid the bare "저변동"/"low volatility" terms so this
        # fundamental row does not displace the existing purely-technical low-volatility
        # menu; it surfaces on quality/defensive intent instead.
        ("우량방어", "우량주", "안정성", "저변동우량", "defensive quality", "quality defensive"),
        ("frazzini_pedersen_bab", "asness_frazzini_pedersen_qmj"),
        lookback=200, direction="asc", mode="scheduled_rotation", risk="defensive", horizon="long", priority=61,
        caveat="유동성 하위 종목은 희박거래로 변동성이 실제보다 낮게 보이는 착시가 있을 수 있습니다.",
    ),
    _r(
        "quality-momentum-overlay", "quality_momentum", "퀄리티-모멘텀 오버레이",
        "ROE가 상위 40%인 우량주 중 200일 추세 위에 있고 6개월 수익이 양수인 종목을 모멘텀 강한 순으로 보유합니다.",
        "rank_top40(ROE) and P>SMA200 and R_126>0; rank=R_126 desc",
        "펀더멘털 우량 필터(ROE 상위)에 가격 추세 확인(200일선 위, 6개월 수익 양수)을 더해 개선되는 우량주의 상승 참여를 노립니다.",
        "우량성만으로 놓치는 타이밍을 가격 모멘텀으로 보완해 결합하기 위해 씁니다(수익성+모멘텀 결합).",
        (_c("roe", GTE, 0.0, universe_rank_pct=.40), _c("close", GT, "sma_200"), _c("return_126d", GT, 0.0)),
        (_c("close", LT, "sma_50"),), "return_126d", ("roe", "return", "sma"),
        ("퀄리티모멘텀", "우량성장", "추세", "quality momentum"),
        ("novy_marx_profitability", "jegadeesh_titman"),
        lookback=200, direction="desc", mode="scheduled_rotation", risk="balanced", horizon="medium", priority=59,
        caveat="청산이 추세선(SMA50) 위주라 회전 성격이 추세추종처럼 보일 수 있습니다.",
    ),
    _r(
        "streak-garp-composite", "garp", "스트릭 기반 GARP",
        "영업이익이 2분기 이상 연속 증가하고 PER은 하위 50%로 비싸지 않으며 ROE가 양수인 흑자 성장주를 ROE 높은 순으로 보유합니다.",
        "operating_income_up_streak>=2 and rank_bottom50(PER) and ROE>0; rank=ROE desc",
        "성장 지속성(영업이익 연속 증가)과 합리적 가격(PER 하위 50%), 흑자 조건을 결합해 비싸게 사지 않는 성장주를 고릅니다.",
        "성장을 좇되 밸류에이션 규율을 함께 걸어 고평가 성장주 위험을 줄이기 위해 씁니다(GARP 적응형, YoY 대신 연속증가 스트릭 사용).",
        (_c("operating_income_up_streak", GTE, 2.0), _c("per", LTE, 0.0, universe_rank_pct=.50), _c("roe", GT, 0.0)),
        (_c("close", LT, "sma_200"),), "roe", ("fundamental_growth_streak", "per", "roe"),
        ("garp", "성장", "저평가성장", "스트릭", "growth", "이익성장", "합리적성장"),
        ("greenblatt_magic_formula",),
        lookback=200, direction="desc", mode="scheduled_rotation", risk="balanced", horizon="medium", priority=57,
        caveat="스트릭은 report_code 없는 직전분기 대비 순차비교라 정상적인 계절 비수기에도 끊길 수 있습니다.",
    ),
    _r(
        "value-quality-momentum-tri", "multi_factor", "밸류-퀄리티-모멘텀 3팩터",
        "PER 하위 50% 저평가·ROE 상위 50% 우량·200일 추세 위 세 조건을 모두 통과한 종목을 상대강도 강한 순으로 보유합니다.",
        "rank_bottom50(PER) and rank_top50(ROE) and P>SMA200; rank=relative_strength_126d desc",
        "밸류(저PER)·퀄리티(고ROE)·모멘텀(추세 위+상대강도)을 순차 스크린으로 결합해 세 팩터가 동시에 우호적인 교집합만 보유합니다.",
        "한 팩터에 의존하지 않고 서로 보완적인 세 팩터를 묶어 안정적인 초과수익을 노리기 위해 씁니다(AQR Value·Momentum + 퀄리티 결합).",
        (_c("per", LTE, 0.0, universe_rank_pct=.50), _c("roe", GTE, 0.0, universe_rank_pct=.50), _c("close", GT, "sma_200")),
        (_c("close", LT, "sma_50"),), "relative_strength_126d", ("per", "roe", "relative_strength", "sma"),
        ("멀티팩터", "밸류퀄리티모멘텀", "3팩터", "복합", "multi factor", "multifactor"),
        ("aqr_value_momentum", "asness_frazzini_pedersen_qmj"),
        lookback=200, direction="desc", mode="scheduled_rotation", risk="balanced", horizon="medium", priority=63,
        caveat="세 팩터를 순차 스크린으로 결합하므로 교집합 종목수가 작아 보유수를 못 채울 수 있습니다.",
    ),
)


assert len(STRATEGY_RULES) >= 50
assert len({rule.strategy_id for rule in STRATEGY_RULES}) == len(STRATEGY_RULES)
