-- Service DB application / AI / backtest ERD aligned to the generated-code execution flow.
-- This migration keeps the existing backtest result tables but shifts the primary
-- execution path toward parse -> code generation -> validation -> sandbox execution.

-- pgcrypto/gen_random_uuid is not created here.
-- Managed PostgreSQL deployments must provision required UUID extensions outside app migrations,
-- or the application must provide UUID values explicitly.
CREATE SCHEMA IF NOT EXISTS app;

DO $$
BEGIN
    CREATE TYPE app.ai_code_status AS ENUM ('generated', 'validated', 'rejected', 'executed', 'failed');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE app.code_execution_status AS ENUM ('queued', 'running', 'succeeded', 'failed', 'timeout');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE app.backtest_execution_mode AS ENUM ('engine', 'ai_generated_code');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS app.users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    name TEXT,
    profile_image_url TEXT,
    password_hash TEXT,
    auth_provider TEXT NOT NULL,
    provider_user_id TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login_at TIMESTAMPTZ,
    UNIQUE (auth_provider, provider_user_id)
);

CREATE INDEX IF NOT EXISTS idx_users_email ON app.users (email);
CREATE INDEX IF NOT EXISTS idx_users_provider_user_id ON app.users (auth_provider, provider_user_id);

CREATE TABLE IF NOT EXISTS app.strategy (
    strategy_id TEXT PRIMARY KEY,
    schema_version TEXT,
    strategy_name TEXT NOT NULL,
    description TEXT,
    user_id BIGINT REFERENCES app.users(user_id),
    market TEXT,
    asset_type TEXT,
    lifecycle TEXT,
    fit_confidence NUMERIC(8, 6),
    spec_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_strategy_user_created ON app.strategy (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS app.ai_chat_session (
    session_id UUID PRIMARY KEY,
    user_id BIGINT REFERENCES app.users(user_id),
    title TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_chat_session_user_created
    ON app.ai_chat_session (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS app.ai_chat_message (
    message_id UUID PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES app.ai_chat_session(session_id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_chat_message_session_created
    ON app.ai_chat_message (session_id, created_at ASC);

CREATE TABLE IF NOT EXISTS app.ai_trace (
    trace_id UUID PRIMARY KEY,
    user_id BIGINT REFERENCES app.users(user_id),
    session_id UUID REFERENCES app.ai_chat_session(session_id),
    trace_kind TEXT NOT NULL DEFAULT 'ai_generated_backtest',
    status TEXT NOT NULL DEFAULT 'running',
    metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_trace_user_started
    ON app.ai_trace (user_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_trace_session_started
    ON app.ai_trace (session_id, started_at DESC);

CREATE TABLE IF NOT EXISTS app.ai_strategy_parse (
    parse_id UUID PRIMARY KEY,
    session_id UUID REFERENCES app.ai_chat_session(session_id),
    user_id BIGINT REFERENCES app.users(user_id),
    trace_id UUID REFERENCES app.ai_trace(trace_id),
    raw_prompt TEXT NOT NULL,
    parsed_strategy_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
    confidence NUMERIC(8, 6),
    model_name TEXT,
    parse_status TEXT NOT NULL DEFAULT 'queued',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_strategy_parse_session_created
    ON app.ai_strategy_parse (session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_strategy_parse_user_created
    ON app.ai_strategy_parse (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_strategy_parse_trace_created
    ON app.ai_strategy_parse (trace_id, created_at DESC);

CREATE TABLE IF NOT EXISTS app.ai_validation_result (
    validation_id UUID PRIMARY KEY,
    parse_id UUID NOT NULL REFERENCES app.ai_strategy_parse(parse_id) ON DELETE CASCADE,
    strategy_id TEXT REFERENCES app.strategy(strategy_id),
    is_valid BOOLEAN NOT NULL,
    warnings_jsonb JSONB NOT NULL DEFAULT '[]'::jsonb,
    errors_jsonb JSONB NOT NULL DEFAULT '[]'::jsonb,
    suggestions_jsonb JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_validation_result_parse_created
    ON app.ai_validation_result (parse_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_validation_result_strategy_created
    ON app.ai_validation_result (strategy_id, created_at DESC);

CREATE TABLE IF NOT EXISTS app.ai_code_generation (
    code_id UUID PRIMARY KEY,
    parse_id UUID REFERENCES app.ai_strategy_parse(parse_id) ON DELETE SET NULL,
    user_id BIGINT REFERENCES app.users(user_id),
    session_id UUID REFERENCES app.ai_chat_session(session_id),
    trace_id UUID REFERENCES app.ai_trace(trace_id),
    source_message_id UUID REFERENCES app.ai_chat_message(message_id),
    target_runtime TEXT NOT NULL,
    code_purpose TEXT NOT NULL,
    generated_code TEXT NOT NULL,
    code_hash TEXT NOT NULL,
    model_name TEXT,
    code_status app.ai_code_status NOT NULL DEFAULT 'generated',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_code_generation_parse_created
    ON app.ai_code_generation (parse_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_code_generation_trace_created
    ON app.ai_code_generation (trace_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_code_generation_status_created
    ON app.ai_code_generation (code_status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_code_generation_hash
    ON app.ai_code_generation (code_hash);

CREATE TABLE IF NOT EXISTS app.ai_code_validation_result (
    validation_id UUID PRIMARY KEY,
    code_id UUID NOT NULL REFERENCES app.ai_code_generation(code_id) ON DELETE CASCADE,
    is_safe BOOLEAN NOT NULL,
    syntax_valid BOOLEAN NOT NULL,
    uses_allowed_imports BOOLEAN NOT NULL,
    blocks_network_access BOOLEAN NOT NULL,
    blocks_file_write BOOLEAN NOT NULL,
    warnings_jsonb JSONB NOT NULL DEFAULT '[]'::jsonb,
    errors_jsonb JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_code_validation_result_code_created
    ON app.ai_code_validation_result (code_id, created_at DESC);

CREATE TABLE IF NOT EXISTS app.code_execution_run (
    execution_run_id UUID PRIMARY KEY,
    code_id UUID NOT NULL REFERENCES app.ai_code_generation(code_id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES app.users(user_id),
    session_id UUID REFERENCES app.ai_chat_session(session_id),
    trace_id UUID REFERENCES app.ai_trace(trace_id),
    runtime_env TEXT NOT NULL,
    sandbox_id TEXT,
    status app.code_execution_status NOT NULL DEFAULT 'queued',
    timeout_seconds INTEGER NOT NULL CHECK (timeout_seconds > 0),
    memory_limit_mb INTEGER NOT NULL CHECK (memory_limit_mb > 0),
    latency_ms NUMERIC(20, 6),
    stdout TEXT,
    stderr TEXT,
    output_artifacts_jsonb JSONB,
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_code_execution_run_code_created
    ON app.code_execution_run (code_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_code_execution_run_trace_created
    ON app.code_execution_run (trace_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_code_execution_run_status_created
    ON app.code_execution_run (status, created_at DESC);

CREATE TABLE IF NOT EXISTS app.backtest_run (
    run_id UUID PRIMARY KEY,
    strategy_id TEXT REFERENCES app.strategy(strategy_id),
    user_id BIGINT REFERENCES app.users(user_id),
    session_id UUID REFERENCES app.ai_chat_session(session_id),
    source_parse_id UUID REFERENCES app.ai_strategy_parse(parse_id),
    code_id UUID REFERENCES app.ai_code_generation(code_id),
    execution_run_id UUID UNIQUE REFERENCES app.code_execution_run(execution_run_id),
    trace_id UUID REFERENCES app.ai_trace(trace_id),
    initial_capital NUMERIC(20, 6) NOT NULL,
    max_tickers INTEGER,
    talib_mode TEXT,
    config_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
    backtest_start_date DATE,
    backtest_end_date DATE,
    benchmark_ticker TEXT,
    data_source TEXT,
    strategy_snapshot_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
    universe_snapshot_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
    as_of_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'queued',
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    error_message TEXT,
    output_paths_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
    execution_mode app.backtest_execution_mode NOT NULL DEFAULT 'engine',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_backtest_run_strategy_created
    ON app.backtest_run (strategy_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_backtest_run_user_created
    ON app.backtest_run (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_backtest_run_session_created
    ON app.backtest_run (session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_backtest_run_parse_created
    ON app.backtest_run (source_parse_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_backtest_run_trace_created
    ON app.backtest_run (trace_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_backtest_run_status_created
    ON app.backtest_run (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_backtest_run_execution_mode_created
    ON app.backtest_run (execution_mode, created_at DESC);

CREATE TABLE IF NOT EXISTS app.backtest_equity_point (
    point_id UUID PRIMARY KEY,
    run_id UUID NOT NULL REFERENCES app.backtest_run(run_id) ON DELETE CASCADE,
    trade_date DATE NOT NULL,
    cash NUMERIC(20, 6),
    positions_value NUMERIC(20, 6),
    total_equity NUMERIC(20, 6),
    daily_return NUMERIC(20, 10),
    UNIQUE (run_id, trade_date)
);

CREATE INDEX IF NOT EXISTS idx_backtest_equity_point_run_trade_date
    ON app.backtest_equity_point (run_id, trade_date ASC);

CREATE TABLE IF NOT EXISTS app.backtest_signal (
    signal_id BIGSERIAL PRIMARY KEY,
    run_id UUID NOT NULL REFERENCES app.backtest_run(run_id) ON DELETE CASCADE,
    signal_date DATE NOT NULL,
    scheduled_execution_date DATE,
    execution_timing TEXT,
    sequence_no INTEGER NOT NULL,
    ticker TEXT NOT NULL,
    action TEXT NOT NULL,
    reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
    matching_entry_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
    matching_exit_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (run_id, sequence_no)
);

CREATE INDEX IF NOT EXISTS idx_backtest_signal_run_signal_date
    ON app.backtest_signal (run_id, signal_date ASC, sequence_no ASC);
CREATE INDEX IF NOT EXISTS idx_backtest_signal_run_ticker
    ON app.backtest_signal (run_id, ticker);

CREATE TABLE IF NOT EXISTS app.backtest_trade (
    trade_id BIGSERIAL PRIMARY KEY,
    run_id UUID NOT NULL REFERENCES app.backtest_run(run_id) ON DELETE CASCADE,
    entry_signal_id BIGINT REFERENCES app.backtest_signal(signal_id),
    exit_signal_id BIGINT REFERENCES app.backtest_signal(signal_id),
    ticker TEXT NOT NULL,
    entry_date DATE NOT NULL,
    exit_date DATE,
    entry_price NUMERIC(20, 6),
    exit_price NUMERIC(20, 6),
    quantity BIGINT,
    entry_cost NUMERIC(20, 6),
    exit_cost NUMERIC(20, 6),
    gross_pnl NUMERIC(20, 6),
    net_pnl NUMERIC(20, 6),
    return_pct NUMERIC(20, 10),
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_backtest_trade_run_entry_date
    ON app.backtest_trade (run_id, entry_date ASC);
CREATE INDEX IF NOT EXISTS idx_backtest_trade_run_ticker
    ON app.backtest_trade (run_id, ticker);

CREATE TABLE IF NOT EXISTS app.backtest_summary (
    summary_id UUID PRIMARY KEY,
    run_id UUID NOT NULL UNIQUE REFERENCES app.backtest_run(run_id) ON DELETE CASCADE,
    final_equity NUMERIC(20, 6),
    final_cash NUMERIC(20, 6),
    open_positions INTEGER,
    period_return NUMERIC(20, 10),
    cagr NUMERIC(20, 10),
    benchmark_return NUMERIC(20, 10),
    alpha NUMERIC(20, 10),
    beta NUMERIC(20, 10),
    max_drawdown NUMERIC(20, 10),
    volatility NUMERIC(20, 10),
    sharpe_ratio NUMERIC(20, 10),
    sortino_ratio NUMERIC(20, 10),
    calmar_ratio NUMERIC(20, 10),
    win_rate NUMERIC(20, 10),
    profit_factor NUMERIC(20, 10),
    payoff_ratio NUMERIC(20, 10),
    avg_win NUMERIC(20, 10),
    avg_loss NUMERIC(20, 10),
    max_consecutive_wins INTEGER,
    max_consecutive_losses INTEGER,
    trade_count INTEGER,
    signal_count INTEGER,
    avg_holding_days NUMERIC(20, 6),
    turnover NUMERIC(20, 10),
    total_commission NUMERIC(20, 6),
    total_tax NUMERIC(20, 6),
    total_slippage NUMERIC(20, 6),
    excluded_ticker_count INTEGER,
    excluded_tickers_jsonb JSONB NOT NULL DEFAULT '[]'::jsonb,
    indicator_report_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
    cost_model_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
    position_sizing_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
    metrics_version TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS app.backtest_metric_detail (
    run_id UUID PRIMARY KEY REFERENCES app.backtest_run(run_id) ON DELETE CASCADE,
    compare_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    composition_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    drawdown_detail_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    drawdown_series_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    greeks_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    rolling_returns_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    monthly_return_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    montecarlo_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    montecarlo_cagr_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    montecarlo_drawdown_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    montecarlo_sharpe_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    outliers_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS app.ai_backtest_report (
    report_id UUID PRIMARY KEY,
    run_id UUID NOT NULL REFERENCES app.backtest_run(run_id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES app.users(user_id),
    trace_id UUID REFERENCES app.ai_trace(trace_id),
    period_return NUMERIC(20, 10),
    cagr NUMERIC(20, 10),
    max_drawdown NUMERIC(20, 10),
    sharpe_ratio NUMERIC(20, 10),
    sortino_ratio NUMERIC(20, 10),
    calmar_ratio NUMERIC(20, 10),
    win_rate NUMERIC(20, 10),
    profit_factor NUMERIC(20, 10),
    volatility NUMERIC(20, 10),
    benchmark_return NUMERIC(20, 10),
    overall_rating TEXT,
    summary TEXT,
    return_analysis TEXT,
    risk_analysis TEXT,
    trade_analysis TEXT,
    benchmark_analysis TEXT,
    improvement_suggestions TEXT,
    report_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
    model_name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_backtest_report_run_created
    ON app.ai_backtest_report (run_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_backtest_report_user_created
    ON app.ai_backtest_report (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_backtest_report_trace_created
    ON app.ai_backtest_report (trace_id, created_at DESC);

CREATE TABLE IF NOT EXISTS app.ai_backtest_report_metric (
    report_metric_id UUID PRIMARY KEY,
    report_id UUID NOT NULL REFERENCES app.ai_backtest_report(report_id) ON DELETE CASCADE,
    run_id UUID REFERENCES app.backtest_run(run_id) ON DELETE CASCADE,
    metric_code TEXT NOT NULL,
    metric_name TEXT NOT NULL,
    metric_group TEXT,
    value_numeric NUMERIC(20, 10),
    value_unit TEXT,
    value_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
    interpretation TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_backtest_report_metric_report_group
    ON app.ai_backtest_report_metric (report_id, metric_group, metric_code);

CREATE TABLE IF NOT EXISTS app.ai_model_call_log (
    call_id UUID PRIMARY KEY,
    trace_id UUID REFERENCES app.ai_trace(trace_id),
    user_id BIGINT REFERENCES app.users(user_id),
    session_id UUID REFERENCES app.ai_chat_session(session_id),
    message_id UUID REFERENCES app.ai_chat_message(message_id),
    code_id UUID REFERENCES app.ai_code_generation(code_id),
    task_type TEXT,
    provider TEXT,
    provider_request_id TEXT,
    model_name TEXT,
    temperature NUMERIC(8, 6),
    top_p NUMERIC(8, 6),
    seed INTEGER,
    prompt_tokens INTEGER,
    completion_tokens INTEGER,
    total_tokens INTEGER,
    latency_ms NUMERIC(20, 6),
    cost NUMERIC(20, 6),
    retry_count INTEGER NOT NULL DEFAULT 0,
    cache_hit BOOLEAN NOT NULL DEFAULT FALSE,
    tool_calls_jsonb JSONB NOT NULL DEFAULT '[]'::jsonb,
    status TEXT NOT NULL DEFAULT 'queued',
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_model_call_log_trace_created
    ON app.ai_model_call_log (trace_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_model_call_log_session_created
    ON app.ai_model_call_log (session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_model_call_log_user_created
    ON app.ai_model_call_log (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_model_call_log_code_created
    ON app.ai_model_call_log (code_id, created_at DESC);

CREATE TABLE IF NOT EXISTS app.ai_prompt_log (
    prompt_log_id UUID PRIMARY KEY,
    call_id UUID NOT NULL UNIQUE REFERENCES app.ai_model_call_log(call_id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES app.users(user_id),
    session_id UUID REFERENCES app.ai_chat_session(session_id),
    prompt_template_name TEXT,
    system_prompt TEXT,
    user_prompt TEXT,
    assistant_response TEXT,
    variables_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
    prompt_version TEXT,
    contains_pii BOOLEAN NOT NULL DEFAULT FALSE,
    masked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_prompt_log_session_created
    ON app.ai_prompt_log (session_id, created_at DESC);

CREATE TABLE IF NOT EXISTS app.ai_agent_execution_log (
    execution_id UUID PRIMARY KEY,
    trace_id UUID REFERENCES app.ai_trace(trace_id),
    user_id BIGINT REFERENCES app.users(user_id),
    session_id UUID REFERENCES app.ai_chat_session(session_id),
    run_id UUID REFERENCES app.backtest_run(run_id),
    execution_run_id UUID REFERENCES app.code_execution_run(execution_run_id),
    agent_name TEXT,
    step_name TEXT,
    status TEXT,
    input_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
    output_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_message TEXT,
    latency_ms NUMERIC(20, 6),
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_ai_agent_execution_log_trace_started
    ON app.ai_agent_execution_log (trace_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_agent_execution_log_session_started
    ON app.ai_agent_execution_log (session_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_agent_execution_log_run_started
    ON app.ai_agent_execution_log (run_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_agent_execution_log_execution_run_started
    ON app.ai_agent_execution_log (execution_run_id, started_at DESC);

CREATE TABLE IF NOT EXISTS app.ai_error_log (
    error_id UUID PRIMARY KEY,
    trace_id UUID REFERENCES app.ai_trace(trace_id),
    user_id BIGINT REFERENCES app.users(user_id),
    session_id UUID REFERENCES app.ai_chat_session(session_id),
    call_id UUID REFERENCES app.ai_model_call_log(call_id),
    execution_id UUID REFERENCES app.ai_agent_execution_log(execution_id),
    execution_run_id UUID REFERENCES app.code_execution_run(execution_run_id),
    error_type TEXT NOT NULL,
    error_message TEXT NOT NULL,
    stack_trace TEXT,
    context_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
    severity TEXT NOT NULL DEFAULT 'error',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_error_log_trace_created
    ON app.ai_error_log (trace_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_error_log_session_created
    ON app.ai_error_log (session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_error_log_call_created
    ON app.ai_error_log (call_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_error_log_execution_created
    ON app.ai_error_log (execution_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_error_log_execution_run_created
    ON app.ai_error_log (execution_run_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_error_log_severity_created
    ON app.ai_error_log (severity, created_at DESC);
